Generate_Ingame("zzzbbbbbbbezzzzzwbubbbbbbbzzzbbbroqoybbbbzbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbzbzbbbbbbbbbbbzbzbbbbbobbbbbbbbbbqbbbbubbbbbbbbobbzzbbzbbbbbrybbzbbzzzbbbbbbbrbbzzzzzbwbbbbbbzzz ")
global.l_title="Octagonistic"
global.l_author="Cage"
global.pathx=119