Generate_Ingame("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzwbbbbbbbbbwzzzbebzqzqzbebzzzbbbbbbbbbbbzzzbzbbbbbbbzbzzzbrbbbbbbbrbzzzbzbbbbbbbzbzzzbbbbbbbbbbbzzzbebztztzbebzzzwbbbbbbbbbwzzzzzzzzzzzzzzzz")
global.l_title="Castle II"
global.l_author="Maurice Zarzycki"
global.pathx=70