package objects.levelMakes
{
   import objects.*;
   
   public function MakeLevel1_2() : void
   {
      Mario.generateBackground(1);
      Mario.levelGenre = 1;
      Mario.musika = 1;
      Mario.level[0] = "gh         fghfggggghfggggggggghfggggggggggggggggggggggggggggggghfgggggghfggggggggggggggggghfggggggghfgggggggggggggghfghfgggggggggggggggggggggggggggggh";
      Mario.level[1] = "gh         fghijjjjjkfggggggggghijjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkfgggggghijjjjjjjjjjjjjjjjjkfggggggghijjjjjjjjjjjjjjkfghijjjjjjjjjjjjjjjjjjjjjjjjjjjjjk";
      Mario.level[2] = "gh         ijk       ijjjjjjjjjk                                 ijjjjjjk                   ijjjjjjjk                fgh                               ";
      Mario.level[3] = "gh                                                                                                                   fgh                               ";
      Mario.level[4] = "gh                                                                                                                   fgh                               ";
      Mario.level[5] = "gh                                                                                                                   fgh                               ";
      Mario.level[6] = "gh                                                                                                                   fgh                               ";
      Mario.level[7] = "gh                                                                                                                   ijk                               ";
      Mario.level[8] = "gh                                                                                                                                                     ";
      Mario.level[9] = "gh                                                                                                                                                     ";
      Mario.level[10] = "gh                                                                                 01                                                                  ";
      Mario.level[11] = "gh                 01                                                              23                                                                  ";
      Mario.level[12] = "ghcddddddddde      23                cdddddde     cdde         cddeQQQ     QQQcdde 23 cdddddddddddddddddddddddddddeM     Mcddddddddddddddddddddddddddde";
      Mario.level[13] = "ghfggggggggghcddddddddddddddddddde   fggggggh     fgghcde   cdefggh           ijjk 23 fggggggggggggggggggggggggggghMM   MMfgggggggggggggggggggggggggggh";
      Mario.level[14] = "ghfggggggggghfgggggggggggggggggggh   fggggggh     fgghfgh   fghfggh                23 fggggggggggggggggggggggggggghMMMMMMMfgggggggggggggggggggggggggggh";
      Mario.levelWid = Mario.level[0].length;
      Mario.levelHei = Mario.level.length;
      Mario.Hud.Time = 320;
      Player.ResetPlayer(150,25);
      Mario.layerWall.addChild(AddGraphic(1950,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(1750,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(1850,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(1650,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(1675,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1700,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1725,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1875,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1900,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1925,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2500,225,"back_crystal_3"));
      Mario.layerWall.addChild(AddGraphic(3150,125,"back_crystal_2"));
      Mario.layerWall.addChild(AddGraphic(1250,225,"back_crystal_3"));
      Mario.layerWall.addChild(AddGraphic(75,200,"back_crystal_1"));
      Mario.drawLevel();
      Mario.instBlocks.push(new Brick(1675,200));
      Mario.instBlocks.push(new Brick(1925,200));
      Mario.instBlocks.push(new Brick(575,250));
      Mario.instBlocks.push(new Brick(600,250));
      Mario.instBlocks.push(new Brick(750,250));
      Mario.instBlocks.push(new Brick(2725,200));
      Mario.instBlocks.push(new Brick(2275,200));
      Mario.instBlocks.push(new Brick(2475,200));
      Mario.instBlocks.push(new Bonus(2600,200,1));
      Mario.instBlocks.push(new BrickMulti(2525,200));
      Mario.instBlocks.push(new Bonus(2625,200,1));
      Mario.instBlocks.push(new Bonus(2750,200,1));
      Mario.instBlocks.push(new Bonus(625,250,1));
      Mario.instBlocks.push(new BrickMulti(775,250));
      Mario.instBlocks.push(new Bonus(725,250,2));
      Mario.instBlocks.push(new Bonus(2250,200,1));
      Mario.instBlocks.push(new Bonus(2375,200,1));
      Mario.instBlocks.push(new Bonus(2400,200,4));
      Mario.instObjects.push(new Coin(475,200));
      Mario.instObjects.push(new Coin(500,200));
      Mario.instObjects.push(new Coin(600,175));
      Mario.instObjects.push(new Coin(750,175));
      Mario.instObjects.push(new Coin(1725,225));
      Mario.instObjects.push(new Coin(1725,200));
      Mario.instObjects.push(new Coin(1875,200));
      Mario.instObjects.push(new Coin(1875,225));
      Mario.instObjects.push(new Coin(2400,150));
      Mario.instObjects.push(new Coin(2475,150));
      Mario.instObjects.push(new Coin(2525,150));
      Mario.instObjects.push(new Coin(2600,150));
      Mario.instObjects.push(new Coin(2750,150));
      Mario.instObjects.push(new Coin(2250,150));
      Mario.instObjects.push(new Coin(2900,300));
      Mario.instObjects.push(new Coin(2925,300));
      Mario.instObjects.push(new Coin(2950,300));
      Mario.instObjects.push(new Coin(2950,275));
      Mario.instObjects.push(new Coin(2975,275));
      Mario.instObjects.push(new Coin(3000,275));
      Mario.instObjects.push(new Coin(3000,300));
      Mario.instObjects.push(new Coin(2975,300));
      Mario.instObjects.push(new Coin(2975,325));
      Mario.instObjects.push(new Coin(2950,325));
      Mario.instObjects.push(new Coin(2925,325));
      Mario.instObjects.push(new Coin(2925,275));
      Mario.instObjects.push(new Coin(2900,275));
      Mario.instObjects.push(new Coin(2925,250));
      Mario.instObjects.push(new Coin(2950,250));
      Mario.instObjects.push(new Coin(2975,250));
      Mario.instEnemies.push(new PPlant(2075,225));
      Mario.instEnemies.push(new TroopaGreen(2950,325));
      Mario.instEnemies.push(new Goomba(2625,275));
      Mario.instEnemies.push(new Goomba(2525,275));
      Mario.instEnemies.push(new Goomba(2475,275));
      Mario.instEnemies.push(new Goomba(2375,275));
      Mario.instEnemies.push(new TroopaRed(2875,275));
      Mario.instEnemies.push(new TroopaRed(2150,275));
      Mario.instEnemies.push(new PPlant(475,250));
      Mario.instEnemies.push(new Goomba(400,300));
      Mario.instEnemies.push(new Goomba(750,225));
      Mario.instEnemies.push(new Goomba(600,225));
      Mario.instEnemies.push(new Goomba(1100,275));
      Mario.instObjects.push(new Coin(975,225));
      Mario.instObjects.push(new Coin(975,250));
      Mario.instObjects.push(new Coin(1050,250));
      Mario.instObjects.push(new Coin(1050,225));
      Mario.instObjects.push(new Coin(1375,275));
      Mario.instObjects.push(new Coin(1525,275));
      Mario.instObjects.push(new Coin(1300,225));
      Mario.instObjects.push(new Coin(1275,225));
      Mario.instObjects.push(new Coin(1600,225));
      Mario.instObjects.push(new Coin(1625,225));
      Mario.instObjects.push(new Finish(3075,275));
      Mario.instEffects.push(new Back(1));
   }
}
