package objects.levelMakes
{
   import objects.*;
   
   public function MakeLevel4_3() : void
   {
      Mario.levelGenre = 2;
      Mario.musika = 0;
      Mario.level[0] = "                                                                                                                                                                                                                                      ";
      Mario.level[1] = "                                                                                                                                                                                                                                      ";
      Mario.level[2] = "                                                                                                                                                                                                                                      ";
      Mario.level[3] = "                                                                                                                                                                                                                                      ";
      Mario.level[4] = "                                                                                                                                                                                                                                      ";
      Mario.level[5] = "                                                                                                                                                                                                                                      ";
      Mario.level[6] = "                     lmnnop                                                                  lmnnnop                                                                                                                                  ";
      Mario.level[7] = "                      qrrs                                   lmnnnop                          qrrrs                                              lmnnnop                                                                              ";
      Mario.level[8] = "           lmnnop     qrrs   S                                qrrrs                           qrrrs                                               qrrrs                                                                               ";
      Mario.level[9] = "            qrrs      qrrs   R   S                            qrrrs     lmnnop       lmnnnop  qrrrs               lmnnop                          qrrrs                                                                               ";
      Mario.level[10] = "            qrrs      qrrs   R S R                     lmnnop qrrrs      qrrs         qrrrs   qrrrs                qrrs                lmnnop     qrrrs                lmnnnnnnnnnop       lmmnnnnnnnoplmnnnnnnnoplmnnnnnoplmnnnnnnnop";
      Mario.level[11] = "   lmnnop   qrrs      qrrs   lmnnnop                    qrrs  qrrrs      qrrs         qrrrs   qrrrs    lmnop       qrrs      lmnop      qrrs      qrrrs                 qrrrrrrrrrs         qrrrrrrrrs  qrrrrrrrs  qrrrrrs  qrrrrrrrs ";
      Mario.level[12] = "    qrrs    qrrs      qrrs    qrrrs                     qrrs  qrrrs      qrrs         qrrrs   qrrrs     qrs        qrrs       qrs       qrrs      qrrrs     lmnnop      qrrrrrrrrrs         qrrrrrrrrs  qrrrrrrrs  qrrrrrs  qrrrrrrrs ";
      Mario.level[13] = "    qrrs    qrrs      qrrs    qrrrs      lmnnnnnnop     qrrs  qrrrs      qrrs         qrrrs   qrrrs     qrs        qrrs       qrs       qrrs      qrrrs      qrrs       qrrrrrrrrrs         qrrrrrrrrs  qrrrrrrrs  qrrrrrs  qrrrrrrrs ";
      Mario.level[14] = "    qrrs    qrrs      qrrs    qrrrs       qrrrrrrs      qrrs  qrrrs      qrrs         qrrrs   qrrrs     qrs        qrrs       qrs       qrrs      qrrrs      qrrs       qrrrrrrrrrs         qrrrrrrrrs  qrrrrrrrs  qrrrrrs  qrrrrrrrs ";
      Mario.levelWid = Mario.level[0].length;
      Mario.levelHei = Mario.level.length;
      Mario.drawLevel();
      Mario.Hud.Time = 320;
      Mario.instEffects.push(new Background(3375,75,"back_clouds_3",0.32));
      Mario.instEffects.push(new Background(2025,25,"back_clouds_3",0.05));
      Mario.instEffects.push(new Background(1000,25,"back_clouds_3",0.19));
      Mario.instEffects.push(new Background(50,200,"back_clouds_3",0.13));
      Mario.instEffects.push(new Background(775,175,"back_clouds_2",0.17));
      Mario.instEffects.push(new Background(2325,150,"back_clouds_2",0.26));
      Mario.instEffects.push(new Background(3875,25,"back_clouds_2",0.14));
      Mario.instEffects.push(new Background(5125,150,"back_clouds_2",0.3));
      Mario.instEffects.push(new Background(4400,50,"back_clouds_1",0.09));
      Mario.instEffects.push(new Background(2725,150,"back_clouds_1",0.09));
      Mario.instEffects.push(new Background(1550,50,"back_clouds_1",0.16));
      Mario.instEffects.push(new Background(300,25,"back_clouds_1",0.16));
      Mario.instEffects.push(new Cloud(125,50));
      Mario.instEffects.push(new Cloud(425,125));
      Mario.instEffects.push(new Cloud(750,25));
      Mario.instEffects.push(new Cloud(900,100));
      Mario.instEffects.push(new Cloud(1300,175));
      Mario.instEffects.push(new Cloud(1350,50));
      Mario.instEffects.push(new Cloud(1775,0));
      Mario.instEffects.push(new Cloud(1975,125));
      Mario.instEffects.push(new Cloud(2200,75));
      Mario.instEffects.push(new Cloud(2675,25));
      Mario.instEffects.push(new Cloud(3250,25));
      Mario.instEffects.push(new Cloud(2900,75));
      Mario.instEffects.push(new Cloud(3100,150));
      Mario.instEffects.push(new Cloud(3525,25));
      Mario.instEffects.push(new Cloud(4025,100));
      Mario.instEffects.push(new Cloud(4650,50));
      Mario.instEffects.push(new Cloud(5300,50));
      Mario.instEffects.push(new Cloud(5000,125));
      Player.ResetPlayer(125,225);
      Mario.instObjects.push(new Finish(4750,225));
      Mario.instEnemies.push(new HammerTroopa(1125,300));
      Mario.instBlocks.push(new Brick(1050,225));
      Mario.instBlocks.push(new Brick(1100,225));
      Mario.instBlocks.push(new Brick(1125,225));
      Mario.instBlocks.push(new Brick(1150,225));
      Mario.instBlocks.push(new Brick(1175,225));
      Mario.instBlocks.push(new Brick(1225,225));
      Mario.instBlocks.push(new Brick(1050,125));
      Mario.instBlocks.push(new Brick(1100,125));
      Mario.instBlocks.push(new Brick(1125,125));
      Mario.instBlocks.push(new Brick(1150,125));
      Mario.instBlocks.push(new Brick(1175,125));
      Mario.instBlocks.push(new Brick(1225,125));
      Mario.instEnemies.push(new HammerTroopa(1150,200));
      Mario.instEnemies.push(new HammerTroopa(1100,100));
      Mario.instObjects.push(new Cannon(775,225));
      Mario.instObjects.push(new Cannon(825,200));
      Mario.instObjects.push(new Cannon(875,250));
      Mario.instObjects.push(new Cannon(725,175));
      Mario.instEnemies.push(new FlyGreen(1625,100));
      Mario.instEnemies.push(new FlyGreen(1575,125));
      Mario.instEnemies.push(new Spiny(1550,150));
      Mario.instEnemies.push(new Spiny(1600,150));
      Mario.instEnemies.push(new Spiny(1650,150));
      Mario.instEnemies.push(new Spiny(1850,200));
      Mario.instEnemies.push(new Spiny(1875,200));
      Mario.instEnemies.push(new TroopaRed(1800,200));
      Mario.instEnemies.push(new TroopaRed(1925,200));
      Mario.instEnemies.push(new Spiny(2350,125));
      Mario.instEnemies.push(new Spiny(2400,125));
      Mario.instEnemies.push(new Spiny(2425,125));
      Mario.instEnemies.push(new Spiny(2375,125));
      Mario.instEnemies.push(new Spiny(2450,125));
      Mario.instEnemies.push(new FlyGreen(2325,100));
      Mario.instEnemies.push(new FlyGreen(2475,100));
      Mario.instEnemies.push(new FlyRed(2700,250));
      Mario.instEnemies.push(new FlyRed(2725,225));
      Mario.instEnemies.push(new FlyRed(2750,150));
      Mario.instEnemies.push(new FlyRed(2775,100));
      Mario.instEnemies.push(new FlyRed(2800,25));
      Mario.instEnemies.push(new FlyRed(3050,175));
      Mario.instEnemies.push(new FlyRed(3075,100));
      Mario.instEnemies.push(new FlyRed(3100,50));
      Mario.instEnemies.push(new FlyRed(3000,275));
      Mario.instEnemies.push(new FlyRed(3025,250));
      Mario.instEnemies.push(new FlyRed(3250,225));
      Mario.instEnemies.push(new FlyRed(3275,200));
      Mario.instEnemies.push(new FlyRed(3300,150));
      Mario.instEnemies.push(new FlyRed(3325,100));
      Mario.instEnemies.push(new FlyRed(3350,125));
      Mario.instEnemies.push(new FlyRed(3575,125));
      Mario.instEnemies.push(new FlyRed(3550,175));
      Mario.instEnemies.push(new FlyRed(3525,75));
      Mario.instEnemies.push(new FlyRed(3600,150));
      Mario.instEnemies.push(new FlyRed(3800,75));
      Mario.instEnemies.push(new FlyRed(3825,125));
      Mario.instEnemies.push(new FlyRed(3850,50));
      Mario.instEnemies.push(new FlyRed(3875,0));
      Mario.instEnemies.push(new FlyRed(4075,275));
      Mario.instEnemies.push(new FlyRed(4100,250));
      Mario.instEnemies.push(new FlyRed(4125,150));
      Mario.instEnemies.push(new FlyGreen(4375,200));
      Mario.instEnemies.push(new FlyGreen(4450,200));
      Mario.instEnemies.push(new FlyGreen(4200,200));
      Mario.instEnemies.push(new FlyGreen(4275,200));
      Mario.instEnemies.push(new Spiny(4250,225));
      Mario.instEnemies.push(new Spiny(4400,225));
      Mario.instEnemies.push(new Spiny(4300,225));
      Mario.instEnemies.push(new Spiny(4350,225));
      Mario.instEnemies.push(new Spiny(4475,225));
      Mario.instEnemies.push(new Spiny(4175,225));
      Mario.instBlocks.push(new Brick(3675,100));
      Mario.instBlocks.push(new Brick(3725,100));
      Mario.instBlocks.push(new Brick(3925,225));
      Mario.instBlocks.push(new Brick(4000,225));
      Mario.instBlocks.push(new Brick(3450,150));
      Mario.instBlocks.push(new Brick(3425,150));
      Mario.instBlocks.push(new Brick(3200,175));
      Mario.instBlocks.push(new Brick(3150,175));
      Mario.instBlocks.push(new Brick(2900,125));
      Mario.instBlocks.push(new Brick(2925,125));
      Mario.instBlocks.push(new Brick(2600,175));
      Mario.instBlocks.push(new Brick(2650,175));
      Mario.instBlocks.push(new Brick(2150,125));
      Mario.instBlocks.push(new Brick(2200,125));
      Mario.instBlocks.push(new Brick(2250,125));
      Mario.instBlocks.push(new Brick(1450,150));
      Mario.instBlocks.push(new Brick(1425,150));
      Mario.instBlocks.push(new Brick(600,75));
      Mario.instBlocks.push(new Brick(575,75));
      Mario.instBlocks.push(new Brick(375,125));
      Mario.instObjects.push(new Cannon(400,175));
      Mario.instObjects.push(new Cannon(275,175));
      Mario.instObjects.push(new Cannon(625,125));
      Mario.instObjects.push(new Cannon(550,125));
      Mario.instObjects.push(new Cannon(1675,150));
      Mario.instObjects.push(new Cannon(2900,200));
      Mario.instObjects.push(new Cannon(2925,200));
      Mario.instObjects.push(new Cannon(3150,250));
      Mario.instObjects.push(new Cannon(3200,250));
      Mario.instObjects.push(new Cannon(3400,225));
      Mario.instObjects.push(new Cannon(3475,225));
      Mario.instObjects.push(new Cannon(3650,150));
      Mario.instObjects.push(new Cannon(3750,150));
      Mario.instObjects.push(new Cannon(3975,275));
      Mario.instObjects.push(new Cannon(3950,275));
      Mario.instBlocks.push(new Bonus(3950,225,2));
      Mario.instBlocks.push(new Bonus(3975,225,1));
      Mario.instBlocks.push(new Bonus(3700,100,1));
      Mario.instBlocks.push(new Bonus(2225,125,1));
      Mario.instBlocks.push(new Bonus(2175,125,1));
      Mario.instBlocks.push(new Bonus(1075,225,1));
      Mario.instBlocks.push(new Bonus(1200,125,1));
      Mario.instBlocks.push(new Bonus(1200,225,3));
      Mario.instBlocks.push(new Bonus(1075,125,3));
      Mario.instObjects.push(new Coin(1075,50));
      Mario.instObjects.push(new Coin(1200,50));
      Mario.instObjects.push(new Coin(1200,175));
      Mario.instObjects.push(new Coin(1075,175));
      Mario.instObjects.push(new Coin(875,200));
      Mario.instObjects.push(new Coin(825,150));
      Mario.instObjects.push(new Coin(775,175));
      Mario.instObjects.push(new Coin(725,125));
      Mario.instObjects.push(new Coin(525,75));
      Mario.instObjects.push(new Coin(650,75));
      Mario.instObjects.push(new Coin(350,125));
      Mario.instObjects.push(new Coin(325,125));
      Mario.instBlocks.push(new Brick(300,125));
      Mario.instObjects.push(new Coin(1200,275));
      Mario.instObjects.push(new Coin(1075,275));
      Mario.instObjects.push(new Coin(1400,175));
      Mario.instObjects.push(new Coin(1475,175));
      Mario.instObjects.push(new Coin(1475,125));
      Mario.instObjects.push(new Coin(1400,125));
      Mario.instObjects.push(new Coin(1575,75));
      Mario.instObjects.push(new Coin(1625,75));
      Mario.instObjects.push(new Coin(1825,150));
      Mario.instObjects.push(new Coin(1900,150));
      Mario.instObjects.push(new Coin(2175,175));
      Mario.instObjects.push(new Coin(2225,175));
      Mario.instObjects.push(new Coin(2400,50));
      Mario.instObjects.push(new Coin(2375,75));
      Mario.instObjects.push(new Coin(2425,75));
      Mario.instObjects.push(new Coin(2625,225));
      Mario.instObjects.push(new Coin(2625,125));
      Mario.instObjects.push(new Coin(2975,150));
      Mario.instObjects.push(new Coin(2850,150));
      Mario.instObjects.push(new Coin(3175,100));
      Mario.instObjects.push(new Coin(3500,125));
      Mario.instObjects.push(new Coin(3375,125));
      Mario.instObjects.push(new Coin(3700,50));
      Mario.instObjects.push(new Coin(3900,175));
      Mario.instObjects.push(new Coin(4025,175));
      Mario.instObjects.push(new Coin(4250,150));
      Mario.instObjects.push(new Coin(4300,150));
      Mario.instObjects.push(new Coin(4350,150));
      Mario.instObjects.push(new Coin(4400,150));
      Mario.instObjects.push(new Coin(4700,175));
      Mario.instBlocks.push(new Bonus(2625,175,1));
      Mario.instBlocks.push(new Bonus(3175,175,1));
      Mario.instEffects.push(new Back(5));
   }
}
