package objects.levelMakes
{
   import objects.*;
   
   public function MakeLevel3_4() : void
   {
      Mario.levelGenre = 3;
      Mario.musika = 2;
      Mario.level[0] = "                                                                                                                                                                                                                          23         ABC                D";
      Mario.level[1] = "                                                                                                                                                                                                                          23         DAB                D";
      Mario.level[2] = "                                                                                                                                                                                                                          23         ABC                D";
      Mario.level[3] = "                                                                                                                                                                                                                          23         DAB                D";
      Mario.level[4] = "                  S                                                                                                           S                    S                                                                      23         ABC                D";
      Mario.level[5] = "                                 S                                                             S      S               S       R         S                     S                                                           45         DAB                D";
      Mario.level[6] = "                         S       R       S                                                     R              S       R       R         R          S                     S                                                                              D";
      Mario.level[7] = "FFFG    EFFG    EFFG    EFFG    EFFG     R            S                   S        S                 EFFG    EFFG    EFFG    EFFG     EFFFG     EFFFG      EFFFFG      EFFFFG     EFFFG    EFFG   EFG  EG M M M M M M                                   D";
      Mario.level[8] = "IIIJ    HIIJ    HIIJ    HIIJ    HIIJ    EFG   EFG   EFG   S           S   R  S    EFG   EFG   EFG    HIIJ    HIIJ    HIIJ    HIIJ     HIIIJ     HIIIJ      HIIIIJ      HIIIIJ     HIIIJ    HIIJ   HIJ  HJ                                               D";
      Mario.level[9] = "IIIJ    HIIJ    HIIJ    HIIJ    HIIJ    HIJ   HIJ   HIJ  EG  EG  EG  EG  EG  EG   HIJ   HIJ   HIJ    HIIJ    HIIJ    HIIJ    HIIJ     HIIIJ     HIIIJ      HIIIIJ      HIIIIJ     HIIIJ    HIIJ   HIJ  HJ                           EFFGOOOOOOOOOOOOOOOOD";
      Mario.level[10] = "IIIJ    HIIJ    HIIJ    HIIJ    HIIJ    HIJ   HIJ   HIJ  HJ  HJ  HJ  HJ  HJ  HJ   HIJ   HIJ   HIJ    HIIJ    HIIJ    HIIJ    HIIJ     HIIIJ     HIIIJ      HIIIIJ      HIIIIJ     HIIIJ    HIIJ   HIJ  HJ                 01       EKIIJ                D";
      Mario.level[11] = "IIILFFFFKIILFFFFKIILFFFFKIILFFFFKIILFFFFKILFFFKILFFFKILFFKLFFKLFFKLFFKJ  HJ  HJ   HIJ   HIJ   HIJ    HIIJ    HIIJ    HIIJ    HIIJ     HIIIJ     HIIIJ      HIIIIJ      HIIIIJ     HIIIJ    HIIJ   HIJ  HJ                 23       HIIIJ                D";
      Mario.level[12] = "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  HJ  HJ   HIJ   HIJ   HIJ    HIIJ    HIIJ    HIIJ    HIIJ     HIIIJ     HIIIJ      HIIIIJ      HIIIIJ     HIIIJ    HIIJ   HIJ  HJ                 23       HIIIJ                D";
      Mario.level[13] = "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  HJ  HJ   HIJ   HIJ   HIJ    HIIJ    HIIJ    HIIJ    HIIJ     HIIIJ     HIIIJ      HIIIIJ      HIIIIJ     HIIIJ    HIIJ   HIJ  HJ                 23       HIIIJ                D";
      Mario.level[14] = "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJ  HJ  HJ   HIJ   HIJ   HIJ    HIIJ    HIIJ    HIIJ    HIIJ     HIIIJ     HIIIJ      HIIIIJ      HIIIIJ     HIIIJ    HIIJ   HIJ  HJ                 23       HIIIJ                D";
      Mario.levelWid = Mario.level[0].length;
      Mario.levelHei = Mario.level.length;
      Mario.drawLevel();
      Mario.Hud.Time = 320;
      Player.ResetPlayer(Mario.checkPoint == 11 ? 5300 : 25,125);
      Mario.instEnemies.push(new Bowser(6025,125,5800,7,2,1,3,8));
      Mario.instObjects.push(new ElevatorLoop(5575,175,25,"elevator_1",2));
      Mario.instEnemies.push(new PPlant(5450,150,-1));
      Mario.instEnemies.push(new PPlant(5450,225));
      Mario.instObjects.push(new Cannon(5100,150));
      Mario.instObjects.push(new Cannon(5250,150));
      Mario.instObjects.push(new Cannon(4700,150));
      Mario.instObjects.push(new Cannon(4500,150));
      Mario.instObjects.push(new Cannon(4225,125));
      Mario.instObjects.push(new Cannon(3950,100));
      Mario.instObjects.push(new Cannon(3950,150));
      Mario.instObjects.push(new Cannon(3675,75));
      Mario.instObjects.push(new Cannon(3675,125));
      Mario.instObjects.push(new Cannon(3450,150));
      Mario.instObjects.push(new Cannon(3400,100));
      Mario.instObjects.push(new Cannon(3150,75));
      Mario.instObjects.push(new Cannon(2950,100));
      Mario.instObjects.push(new Cannon(2750,125));
      Mario.instObjects.push(new Cannon(2550,150));
      Mario.instObjects.push(new Cannon(2550,100));
      Mario.instObjects.push(new Cannon(2375,100));
      Mario.instObjects.push(new Cannon(2375,175));
      Mario.instObjects.push(new Cannon(2225,150));
      Mario.instObjects.push(new Cannon(2225,125));
      Mario.instObjects.push(new Cannon(2225,175));
      Mario.instObjects.push(new Cannon(2075,150));
      Mario.instObjects.push(new Cannon(1925,175));
      Mario.instObjects.push(new Cannon(1850,150));
      Mario.instObjects.push(new Cannon(1750,175));
      Mario.instObjects.push(new Cannon(1625,200));
      Mario.instObjects.push(new Cannon(1550,200));
      Mario.instObjects.push(new Cannon(1450,175));
      Mario.instObjects.push(new Cannon(1350,150));
      Mario.instObjects.push(new Cannon(1150,175));
      Mario.instObjects.push(new Cannon(1025,125));
      Mario.instObjects.push(new Cannon(825,100));
      Mario.instObjects.push(new Cannon(625,125));
      Mario.instObjects.push(new Cannon(450,75));
      Mario.instObjects.push(new Cannon(450,125));
      Mario.instObjects.push(new Cannon(450,150));
      Mario.instObjects.push(new Cannon(250,150));
      Mario.instEnemies.push(new Spiny(975,250));
      Mario.instEnemies.push(new Spiny(750,250));
      Mario.instEnemies.push(new Spiny(525,250));
      Mario.instEnemies.push(new Spiny(350,250));
      Mario.instEnemies.push(new Spiny(150,250));
      Mario.instEnemies.push(new Spiny(1250,250));
      Mario.instEnemies.push(new Spiny(1125,250));
      Mario.instEnemies.push(new PPlant(1375,250));
      Mario.instEnemies.push(new PPlant(1475,250));
      Mario.instEnemies.push(new PPlant(1575,250));
      Mario.instEnemies.push(new PPlant(1675,250));
      Mario.instEnemies.push(new FlyRed(2000,50));
      Mario.instEnemies.push(new FlyRed(2150,100));
      Mario.instEnemies.push(new FlyRed(2300,75));
      Mario.instEnemies.push(new FlyRed(2450,100));
      Mario.instEnemies.push(new FlyRed(2650,50));
      Mario.instEnemies.push(new FlyRed(2875,75));
      Mario.instEnemies.push(new FlyRed(3050,100));
      Mario.instEnemies.push(new FlyRed(3250,25));
      Mario.instEnemies.push(new FlyRed(3300,125));
      Mario.instEnemies.push(new FlyRed(3500,75));
      Mario.instEnemies.push(new FlyRed(3550,25));
      Mario.instEnemies.push(new FlyRed(3750,125));
      Mario.instEnemies.push(new FlyRed(3800,50));
      Mario.instEnemies.push(new FlyRed(4050,75));
      Mario.instEnemies.push(new FlyRed(4125,100));
      Mario.instEnemies.push(new FlyRed(4350,125));
      Mario.instEnemies.push(new FlyRed(4400,50));
      Mario.instEnemies.push(new FlyRed(4625,100));
      Mario.instEnemies.push(new FlyRed(4800,75));
      Mario.instEnemies.push(new FlyRed(5350,75));
      Mario.instEnemies.push(new FlyRed(5375,125));
      Mario.instEnemies.push(new FlyRed(5400,200));
      Mario.instObjects.push(new Coin(5300,100));
      Mario.instObjects.push(new Coin(5200,100));
      Mario.instObjects.push(new Coin(5150,100));
      Mario.instObjects.push(new Coin(5050,100));
      Mario.instObjects.push(new Coin(5100,50));
      Mario.instObjects.push(new Coin(5250,50));
      Mario.instObjects.push(new Coin(4875,100));
      Mario.instObjects.push(new Coin(4500,75));
      Mario.instObjects.push(new Coin(4700,75));
      Mario.instObjects.push(new Coin(4225,50));
      Mario.instObjects.push(new Coin(3950,25));
      Mario.instObjects.push(new Coin(3675,25));
      Mario.instObjects.push(new Coin(3675,0));
      Mario.instObjects.push(new Coin(3950,50));
      Mario.instObjects.push(new Coin(4225,75));
      Mario.instObjects.push(new Coin(4500,100));
      Mario.instObjects.push(new Coin(4700,100));
      Mario.instObjects.push(new Coin(3400,50));
      Mario.instObjects.push(new Coin(3400,25));
      Mario.instObjects.push(new Coin(3450,100));
      Mario.instObjects.push(new Coin(3450,75));
      Mario.instObjects.push(new Coin(3150,25));
      Mario.instObjects.push(new Coin(3150,0));
      Mario.instObjects.push(new Coin(2950,50));
      Mario.instObjects.push(new Coin(2950,25));
      Mario.instObjects.push(new Coin(2750,50));
      Mario.instObjects.push(new Coin(2750,75));
      Mario.instObjects.push(new Coin(2550,50));
      Mario.instObjects.push(new Coin(2550,25));
      Mario.instObjects.push(new Coin(2375,25));
      Mario.instObjects.push(new Coin(2375,50));
      Mario.instObjects.push(new Coin(2225,75));
      Mario.instObjects.push(new Coin(2225,50));
      Mario.instObjects.push(new Coin(2075,100));
      Mario.instObjects.push(new Coin(2075,75));
      Mario.instObjects.push(new Coin(1925,100));
      Mario.instObjects.push(new Coin(1925,125));
      Mario.instObjects.push(new Coin(1850,100));
      Mario.instObjects.push(new Coin(1850,75));
      Mario.instObjects.push(new Coin(1750,125));
      Mario.instObjects.push(new Coin(1750,100));
      Mario.instObjects.push(new Coin(1625,150));
      Mario.instObjects.push(new Coin(1625,125));
      Mario.instObjects.push(new Coin(1550,125));
      Mario.instObjects.push(new Coin(1550,150));
      Mario.instObjects.push(new Coin(1450,125));
      Mario.instObjects.push(new Coin(1450,100));
      Mario.instObjects.push(new Coin(1350,100));
      Mario.instObjects.push(new Coin(1350,75));
      Mario.instObjects.push(new Coin(1150,125));
      Mario.instObjects.push(new Coin(1150,100));
      Mario.instObjects.push(new Coin(1025,75));
      Mario.instObjects.push(new Coin(1025,50));
      Mario.instObjects.push(new Coin(825,50));
      Mario.instObjects.push(new Coin(825,25));
      Mario.instObjects.push(new Coin(625,75));
      Mario.instObjects.push(new Coin(625,50));
      Mario.instObjects.push(new Coin(450,25));
      Mario.instObjects.push(new Coin(450,0));
      Mario.instObjects.push(new Coin(250,100));
      Mario.instObjects.push(new Coin(250,75));
      Mario.instBlocks.push(new Bonus(625,0,2,true));
      Mario.instBlocks.push(new Bonus(250,25,3,true));
      Mario.instBlocks.push(new Bonus(1150,50,3,true));
      Mario.instBlocks.push(new Bonus(1350,25,3,true));
      Mario.instBlocks.push(new Bonus(3175,100,4,true));
      Mario.instBlocks.push(new Bonus(4250,125,2,true));
      Mario.instBlocks.push(new BrickMulti(5100,25));
      Mario.instBlocks.push(new BrickMulti(5250,25));
      Mario.instEffects.push(new Back(3));
   }
}
