package objects.levelMakes
{
   import objects.*;
   
   internal function MakeLevel1_1() : void
   {
      Mario.levelGenre = 0;
      Mario.musika = 0;
      Mario.generateBackground(0);
      Mario.level[0] = "                                                                                                                                                   ";
      Mario.level[1] = "                                                                                                                                                   ";
      Mario.level[2] = "                                                                                                                                                   ";
      Mario.level[3] = "                                                                                                                                                   ";
      Mario.level[4] = "                                                                                                                                                   ";
      Mario.level[5] = "                                                                                                                                                   ";
      Mario.level[6] = "                                                                                                                                                   ";
      Mario.level[7] = "                                                                                                                                                   ";
      Mario.level[8] = "                                            01         01                                                                                          ";
      Mario.level[9] = "                                  01        23         23          MM   MM                                                                         ";
      Mario.level[10] = "                       01         23        23         23                                                                                          ";
      Mario.level[11] = "                       23         23        23         23                               01                M                                        ";
      Mario.level[12] = "dddddddddddddeM   McdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeQQQQQQQQQQQce                                        ";
      Mario.level[13] = "ggggggggggggghMM MMfgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggh           fhcdddddddddddddddddddddddddddddddddddddde";
      Mario.level[14] = "jjjjjjjjjjjjjkMMMMMfgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggh           fhfggggggggggggggggggggggggggggggggggggggh";
      Mario.levelWid = Mario.level[0].length;
      Mario.levelHei = Mario.level.length;
      Mario.drawLevel();
      Mario.Hud.Time = 320;
      Player.ResetPlayer(25,250);
      Mario.layerWall.addChild(AddGraphic(2775,300,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(3100,300,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(3075,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3050,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3025,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3000,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2975,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2950,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2925,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2900,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2875,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2850,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2825,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2800,300,"back_fence_2"));
      Mario.instEffects.push(new Background(2975,100,"back_clouds_7",0.4));
      Mario.instEffects.push(new Background(1725,125,"back_clouds_8",0.74));
      Mario.instEffects.push(new Background(25,100,"back_clouds_7",0.48));
      Mario.instEffects.push(new Background(775,150,"back_clouds_4",0.52));
      Mario.instEffects.push(new Background(525,100,"back_clouds_1",0.26));
      Mario.instEffects.push(new Background(1975,100,"back_clouds_1",0.14));
      Mario.instEffects.push(new Background(300,275,"back_hill",0.11));
      Mario.instEffects.push(new Cloud(3025,50));
      Mario.instEffects.push(new Cloud(2725,100));
      Mario.instEffects.push(new Cloud(2225,25));
      Mario.instEffects.push(new Cloud(1825,75));
      Mario.instEffects.push(new Cloud(25,25));
      Mario.instEffects.push(new Cloud(425,75));
      Mario.instEffects.push(new Cloud(675,50));
      Mario.instEffects.push(new Cloud(1000,100));
      Mario.instEffects.push(new Cloud(1425,50));
      Mario.layerWall.addChild(AddGraphic(1900,250,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(1900,225,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(1750,200,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(1750,225,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(1750,250,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(1700,250,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(1900,200,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(1750,175,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(1700,225,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(1425,250,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(1200,225,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(175,100,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(175,125,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(175,150,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(175,175,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(175,200,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(2325,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(1475,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(1950,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(1600,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(2150,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(2625,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(2600,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2575,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2550,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2525,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2500,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2475,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2450,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2425,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2400,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2375,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2350,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1975,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2000,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2025,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2050,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2075,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2100,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2125,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1575,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1550,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1525,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1500,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1000,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(500,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(550,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(525,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(975,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(950,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(925,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(900,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(625,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(650,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(675,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(700,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(725,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(750,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(775,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(800,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(825,275,"back_fence_2"));
      Mario.instObjects.push(new Finish(2725,300));
      Mario.instBlocks.push(new Brick(175,200));
      Mario.instBlocks.push(new Brick(200,200));
      Mario.instBlocks.push(new Brick(275,200));
      Mario.instBlocks.push(new Bonus(125,200,1));
      Mario.instBlocks.push(new Bonus(250,200,1));
      Mario.instBlocks.push(new Bonus(100,125,2));
      Mario.instBlocks.push(new Bonus(275,125,1));
      Mario.instBlocks.push(new BrickMulti(300,200));
      Mario.instBlocks.push(new BrickMulti(75,200));
      Mario.instBlocks.push(new Brick(100,200));
      Mario.instBlocks.push(new Brick(1100,75));
      Mario.instBlocks.push(new BrickMulti(1125,75));
      Mario.instBlocks.push(new Bonus(1725,225,1));
      Mario.instBlocks.push(new Bonus(1775,225,1));
      Mario.instBlocks.push(new Brick(1750,225));
      Mario.instBlocks.push(new Bonus(100,25,4,true));
      Mario.instBlocks.push(new Bonus(2375,200,1));
      Mario.instBlocks.push(new Bonus(2575,200,1));
      Mario.instObjects.push(new Coin(2375,125));
      Mario.instObjects.push(new Coin(2375,150));
      Mario.instObjects.push(new Coin(2575,150));
      Mario.instObjects.push(new Coin(2575,125));
      Mario.instObjects.push(new Coin(1700,150));
      Mario.instObjects.push(new Coin(1725,150));
      Mario.instObjects.push(new Coin(1800,150));
      Mario.instObjects.push(new Coin(1775,150));
      Mario.instObjects.push(new Coin(1675,250));
      Mario.instObjects.push(new Coin(1825,250));
      Mario.instObjects.push(new Coin(1700,250));
      Mario.instObjects.push(new Coin(1800,250));
      Mario.instObjects.push(new Coin(1375,125));
      Mario.instObjects.push(new Coin(1400,125));
      Mario.instObjects.push(new Coin(1100,125));
      Mario.instObjects.push(new Coin(1125,125));
      Mario.instObjects.push(new Coin(875,150));
      Mario.instObjects.push(new Coin(850,150));
      Mario.instObjects.push(new Coin(600,175));
      Mario.instObjects.push(new Coin(575,175));
      Mario.instObjects.push(new Coin(375,300));
      Mario.instObjects.push(new Coin(400,300));
      Mario.instObjects.push(new Coin(400,325));
      Mario.instObjects.push(new Coin(425,300));
      Mario.instObjects.push(new Coin(375,275));
      Mario.instObjects.push(new Coin(400,275));
      Mario.instObjects.push(new Coin(425,275));
      Mario.instObjects.push(new Coin(400,250));
      Mario.instObjects.push(new Coin(100,100));
      Mario.instObjects.push(new Coin(275,100));
      Mario.instObjects.push(new Coin(275,175));
      Mario.instObjects.push(new Coin(100,175));
      Mario.instObjects.push(new Coin(200,150));
      Mario.instObjects.push(new Coin(175,150));
      Mario.instEnemies.push(new Goomba(325,275));
      Mario.instEnemies.push(new Goomba(750,275));
      Mario.instEnemies.push(new Goomba(1025,275));
      Mario.instEnemies.push(new Goomba(1250,275));
      Mario.instEnemies.push(new Goomba(1900,275));
      Mario.instEnemies.push(new Goomba(1800,200));
      Mario.instEnemies.push(new Goomba(2600,275));
      Mario.layerWall.addChild(AddGraphic(175,275,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(175,250,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(175,225,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(1200,275,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(1200,250,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(1425,275,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(1700,275,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(1750,275,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(1900,275,"back_tree_2"));
   }
}
