package objects.levelMakes
{
   import objects.*;
   
   public function MakeLevel2_2() : void
   {
      Mario.levelGenre = 0;
      Mario.musika = 1;
      Mario.level[0] = "                                                                                                                                                                                                                                     ";
      Mario.level[1] = "                                                                                                                                                                                                                                     ";
      Mario.level[2] = "                                                                                                                                                                                                                                     ";
      Mario.level[3] = "                                                                                                                                                                                                                                     ";
      Mario.level[4] = "                                                                                                                                                                                                                                     ";
      Mario.level[5] = "                                                                                                                                    S                                           lmnnop                                               ";
      Mario.level[6] = "                                                                                                                                  lmnop                                          qrrs                                                ";
      Mario.level[7] = "                          lmnnnop                                                                                                  qrs                                           qrrs                                                ";
      Mario.level[8] = "                           qrrrs                               01                      01                                          qrs                                           qrrs                                                ";
      Mario.level[9] = "  lmnopQQQQlmop            qrrrs     lmnnop                    23                      23                 lmnnnnop         lmnop   qrs                                           qrrs                                                ";
      Mario.level[10] = "   qrs      qs             qrrrs      qrrs                     23                      23                  qrrrrs           qrs    qrs                         lmnop             qrrs                                                ";
      Mario.level[11] = "   qrs      qs     lmnop   qrrrs      qrrs                     23                      23                  qrrrrs           qrs    qrs                          qrs              qrrs                                                ";
      Mario.level[12] = "   qrs      qs      qrs    qrrrs      qrrs                     23                      23                  qrrrrs           qrs    qrs   lmnop   lmop  lmnop    qrs              qrrs                                                ";
      Mario.level[13] = "   qrs      qs      qrs    qrrrs      qrrs                     23                      23                  qrrrrs           qrs    qrs    qrs     qs    qrs     qrs              qrrs       cddddddddddddddddddddddddddddddddddddddde";
      Mario.level[14] = "   qrs      qs      qrs    qrrrs      qrrs                     23                      23                  qrrrrs           qrs    qrs    qrs     qs    qrs     qrs              qrrs       fgggggggggggggggggggggggggggggggggggggggh";
      Mario.levelWid = Mario.level[0].length;
      Mario.levelHei = Mario.level.length;
      Mario.drawLevel();
      Mario.Hud.Time = 320;
      Mario.instEffects.push(new Background(2100,175,"back_forest_4",0.88));
      Mario.instEffects.push(new Background(0,175,"back_forest_4",0.85));
      Mario.instEffects.push(new Background(4300,200,"back_forest_1",0.31));
      Mario.instEffects.push(new Background(1325,175,"back_clouds_1",0.3));
      Mario.instEffects.push(new Background(3125,75,"back_clouds_2",0.25));
      Mario.instEffects.push(new Background(3050,200,"back_forest_1",0.24));
      Mario.instEffects.push(new Background(4100,275,"back_forest_2",0.21));
      Mario.instEffects.push(new Background(1650,225,"back_forest_3",0.2));
      Mario.instEffects.push(new Background(4050,75,"back_clouds_3",0.18));
      Mario.instEffects.push(new Background(4775,25,"back_clouds_2",0.17));
      Mario.instEffects.push(new Background(3600,225,"back_forest_3",0.17));
      Mario.instEffects.push(new Background(2100,0,"back_clouds_1",0.14));
      Mario.instEffects.push(new Background(5275,150,"back_clouds_3",0.12));
      Mario.instEffects.push(new Background(650,0,"back_clouds_1",0.09));
      Mario.instEffects.push(new Background(75,50,"back_clouds_3",0.05));
      Mario.layerWall.addChild(AddGraphic(3800,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(3900,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(3875,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3850,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3825,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3950,225,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(4050,225,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(3975,225,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4000,225,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4025,225,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5150,250,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(5025,175,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(5025,200,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(5025,225,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(4825,125,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(4825,150,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(4825,200,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(4825,175,"back_tree_3"));
      Mario.instEffects.push(new Background(4825,175,"back_forest_4",0.919999957));
      Mario.layerWall.addChild(AddGraphic(4675,300,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(5075,300,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(5050,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5025,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5000,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4975,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4950,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4925,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4900,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4875,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4850,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4825,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4800,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4775,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4750,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4725,300,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4700,300,"back_fence_2"));
      Mario.instEffects.push(new Cloud(5350,25));
      Mario.instEffects.push(new Cloud(5000,125));
      Mario.instEffects.push(new Cloud(5175,200));
      Mario.instEffects.push(new Cloud(4625,200));
      Mario.instEffects.push(new Cloud(3625,25));
      Mario.instEffects.push(new Cloud(2850,75));
      Mario.instEffects.push(new Cloud(2350,0));
      Mario.instEffects.push(new Cloud(1725,50));
      Mario.instEffects.push(new Cloud(1475,75));
      Mario.instEffects.push(new Cloud(900,150));
      Mario.instEffects.push(new Cloud(375,50));
      Player.ResetPlayer(100,175);
      Mario.instObjects.push(new Finish(4750,300));
      Mario.instBlocks.push(new Bonus(525,175,1));
      Mario.instBlocks.push(new Bonus(1175,125,1));
      Mario.instBlocks.push(new Bonus(1350,125,1));
      Mario.instBlocks.push(new Bonus(1800,125,1));
      Mario.instBlocks.push(new Bonus(1975,125,1));
      Mario.instBlocks.push(new Bonus(2425,125,1));
      Mario.instBlocks.push(new Bonus(2675,125,1));
      Mario.instBlocks.push(new Bonus(2800,125,1));
      Mario.instBlocks.push(new Bonus(3125,125,1));
      Mario.instBlocks.push(new Bonus(3425,200,1));
      Mario.instBlocks.push(new Bonus(3525,200,1));
      Mario.instBlocks.push(new Bonus(3825,200,1));
      Mario.instBlocks.push(new Bonus(4025,150,1));
      Mario.instBlocks.push(new Bonus(3675,200,2));
      Mario.instBlocks.push(new Brick(3800,200));
      Mario.instBlocks.push(new Brick(3850,200));
      Mario.instBlocks.push(new Brick(3100,125));
      Mario.instBlocks.push(new Brick(2700,125));
      Mario.instBlocks.push(new Brick(2775,125));
      Mario.instBlocks.push(new Brick(2375,125));
      Mario.instBlocks.push(new Brick(2350,125));
      Mario.instBlocks.push(new Brick(2475,125));
      Mario.instBlocks.push(new Brick(2500,125));
      Mario.instBlocks.push(new Brick(1900,125));
      Mario.instBlocks.push(new Brick(1875,125));
      Mario.instBlocks.push(new Brick(1250,125));
      Mario.instBlocks.push(new Brick(1000,100));
      Mario.instBlocks.push(new BrickMulti(975,100));
      Mario.instBlocks.push(new BrickMulti(1275,125));
      Mario.instBlocks.push(new BrickMulti(3150,125));
      Mario.instObjects.push(new Coin(525,125));
      Mario.instObjects.push(new Coin(1175,75));
      Mario.instObjects.push(new Coin(1275,50));
      Mario.instObjects.push(new Coin(1250,50));
      Mario.instObjects.push(new Coin(1350,75));
      Mario.instObjects.push(new Coin(1800,75));
      Mario.instObjects.push(new Coin(1875,50));
      Mario.instObjects.push(new Coin(1900,50));
      Mario.instObjects.push(new Coin(1975,75));
      Mario.instObjects.push(new Coin(2350,50));
      Mario.instObjects.push(new Coin(2375,50));
      Mario.instObjects.push(new Coin(2425,75));
      Mario.instObjects.push(new Coin(2500,50));
      Mario.instObjects.push(new Coin(2475,50));
      Mario.instObjects.push(new Coin(2700,75));
      Mario.instObjects.push(new Coin(2775,75));
      Mario.instObjects.push(new Coin(3125,50));
      Mario.instObjects.push(new Coin(3525,125));
      Mario.instObjects.push(new Coin(3425,125));
      Mario.instObjects.push(new Coin(3650,125));
      Mario.instObjects.push(new Coin(3675,125));
      Mario.instObjects.push(new Coin(4050,150));
      Mario.instObjects.push(new Coin(4000,150));
      Mario.instObjects.push(new ElevatorFall(4325,125,50,"elevator_2"));
      Mario.instObjects.push(new ElevatorFall(4225,175,50,"elevator_2"));
      Mario.instObjects.push(new ElevatorFall(4125,225,50,"elevator_2"));
      Mario.instObjects.push(new ElevatorFall(2925,225,75,"elevator_3"));
      Mario.instObjects.push(new ElevatorBounce(2450,225,75,"elevator_3",2));
      Mario.instObjects.push(new ElevatorBounce(1275,225,75,"elevator_3",2));
      Mario.instObjects.push(new ElevatorBounce(1875,225,75,"elevator_3",2));
      Mario.instObjects.push(new Coin(4150,200));
      Mario.instObjects.push(new Coin(4125,200));
      Mario.instObjects.push(new Coin(4225,150));
      Mario.instObjects.push(new Coin(4250,150));
      Mario.instObjects.push(new Coin(4325,100));
      Mario.instObjects.push(new Coin(4350,100));
      Mario.instObjects.push(new Coin(2150,200));
      Mario.instObjects.push(new Coin(2125,200));
      Mario.instObjects.push(new Coin(2250,200));
      Mario.instObjects.push(new Coin(2225,200));
      Mario.instObjects.push(new Coin(1650,200));
      Mario.instObjects.push(new Coin(1625,200));
      Mario.instObjects.push(new Coin(1550,200));
      Mario.instObjects.push(new Coin(1525,200));
      Mario.instObjects.push(new Coin(300,150));
      Mario.instObjects.push(new Coin(300,125));
      Mario.instObjects.push(new Coin(325,125));
      Mario.instObjects.push(new Coin(325,150));
      Mario.instEnemies.push(new PPlant(2175,175));
      Mario.instEnemies.push(new PPlant(1575,175));
      Mario.instEnemies.push(new PStatic(725,150));
      Mario.instEnemies.push(new PStatic(700,150));
      Mario.instEnemies.push(new PStatic(750,150));
      Mario.instEnemies.push(new PStatic(2725,200));
      Mario.instEnemies.push(new PStatic(2750,200));
      Mario.instEnemies.push(new PStatic(4450,100));
      Mario.instEnemies.push(new PStatic(4475,100));
      Mario.instEnemies.push(new FlyRed(4575,75));
      Mario.instEnemies.push(new FlyRed(4650,175));
      Mario.instEnemies.push(new FlyRed(2275,100));
      Mario.instEnemies.push(new FlyRed(2075,125));
      Mario.instEnemies.push(new FlyRed(1700,150));
      Mario.instEnemies.push(new FlyRed(1475,25));
      Mario.instEnemies.push(new FlyRed(1100,125));
      Mario.instEnemies.push(new FlyRed(850,150));
      Mario.instEnemies.push(new FlyRed(2575,75));
      Mario.instEnemies.push(new FlyRed(2950,150));
      Mario.instEnemies.push(new TroopaRed(3150,200));
      Mario.instEnemies.push(new TroopaRed(3500,275));
      Mario.instEnemies.push(new TroopaRed(1000,200));
      Mario.instObjects.push(new Cannon(3300,100));
      Mario.instBlocks.push(new Bonus(3650,200,3));
      Mario.instBlocks.push(new Bonus(3825,75,4,true));
      Mario.layerWall.addChild(AddGraphic(4825,300,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(4825,275,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(4825,250,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(4825,225,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(5025,300,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(5025,275,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(5025,250,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(5150,300,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(5150,275,"back_tree_2"));
      Mario.instEnemies.push(new Spiny(350,200));
      Mario.instEnemies.push(new Spiny(300,200));
      Mario.instBlocks.push(new Bonus(50,125,1,true));
      Mario.instBlocks.push(new Bonus(50,25,4,true));
      Mario.instObjects.push(new Coin(200,150));
      Mario.instObjects.push(new Coin(225,150));
   }
}
