package objects.levelMakes
{
   import objects.*;
   
   public function MakeLevel4_1() : void
   {
      Mario.levelGenre = 2;
      Mario.musika = 0;
      Mario.level[0] = "                                                                                                                                                                                                                                                                         ";
      Mario.level[1] = "                                                                                                                                                                                                                                                                         ";
      Mario.level[2] = "                                                                                                                                                                                                                                                                         ";
      Mario.level[3] = "                                                                                                                                                                                           M        M                                                                    ";
      Mario.level[4] = "                                                                                                                                     MM                                          M                       M      M       M     M   M                                      ";
      Mario.level[5] = "                                                                                              MMMMMM       MMMMMM  MMMMMM            MM        M   M   M   M   M   M      M   M               M  M                 M       M                                             ";
      Mario.level[6] = "                                                                                              MMMMMM       MMMMMM  MMMMMM      MMMM            M   M   M   M   M   M                  M             M M    M                   M                                         ";
      Mario.level[7] = "                                                                                              MM           MM        MM        MMMM       MMM MMM MMM MMM MMM MMM MMM        M   M      M   M                 M      M  MM  M                                            ";
      Mario.level[8] = "                                                                                            MMMM           MM        MM          MMMM     MMM MMM MMM MMM MMM MMM MMM              M            M              M                                                         ";
      Mario.level[9] = "                                  MMMM    MMMM       MMMMMMMMMMMMMMMM    01                 MMMM           MM        MM          MMMM     MMM MMM MMM MMM MMM MMM MMM     M   M                       MM    M              M   M                                         ";
      Mario.level[10] = "                          MMM     MMMM    MMMM       MMMMMMMMMMMMMMMMM   23                 MMMM  MMMMMMMMMMM        MM            MMMM    M   M   M   M   M   M   M           M       M   M  M    M             M   M      M                                            ";
      Mario.level[11] = "                    MM    MM       MM                    MM    MM        23               MMMMMM  MMM     MMM        MM            MMMM    M   M   M   M   M   M   M             M  M                        M                   M                                       ";
      Mario.level[12] = "            01      MM    MM       MM                 MM MM MM MM MM     23       ce      MMMMMM                                             M   M   M   M   M   M        MQQQQQQQQQQQQQQQM MQQQQQQQQQQQM MQQQQQQQQQQQQM MQQQQQQQQM                                      ";
      Mario.level[13] = "       M    23      MM    MM               MM         MM    MM    MM     23       fh      MMMMMM                                             M   M   M   M   M   M        M                                                       M                                      ";
      Mario.level[14] = "ddddde cdde ce  cde ce ce ce     cddde  ce cde  cde  cdddddddddddddddde  23 ce    fh    MMMMMMMM cddde   cdddde  cddddddde  cddddddddddde   cde cde cde cde cde cde cddddde                                                       Mcddddddddddddddddddddddddddddddddddddd";
      Mario.levelWid = Mario.level[0].length;
      Mario.levelHei = Mario.level.length;
      Mario.drawLevel();
      Mario.Hud.Time = 320;
      Mario.layerWall.addChild(AddGraphic(75,300,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(75,275,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(400,275,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(400,225,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(400,250,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(1000,300,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(1225,275,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(1900,275,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(1900,250,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(2875,275,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(3100,275,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(3100,250,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(3100,225,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(4175,200,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(4175,225,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(4175,250,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(5725,300,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(5800,275,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(5800,250,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(5925,250,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(5925,225,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(6000,275,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(6000,250,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(6000,225,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(6075,275,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(6200,300,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(6300,275,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(6300,250,"back_tree_3"));
      Mario.layerWall.addChild(AddGraphic(6300,225,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(5925,200,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(6000,200,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(6075,250,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(6200,275,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(5875,300,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(5800,225,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(5725,275,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(4175,175,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(3100,200,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(2875,250,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(1900,225,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(1225,250,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(1000,275,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(825,275,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(400,200,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(225,250,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(75,250,"back_tree_4"));
      Mario.layerWall.addChild(AddGraphic(550,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(1175,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(1300,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(2025,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(2450,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(2675,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(2800,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(2900,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(3150,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(3350,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(3475,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(3575,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(3675,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(3775,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(3875,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(3975,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(4125,325,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(4075,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(3975,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(3875,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(3775,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(3675,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(3575,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(3425,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(3275,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(3000,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(2850,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(2775,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(2525,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(2100,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(1750,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(1225,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(1150,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(625,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(250,325,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(200,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(225,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(575,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(600,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1125,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1200,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1325,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1725,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1700,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2050,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2075,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2475,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2500,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2700,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2725,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2750,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2825,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2925,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2950,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2975,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3400,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3375,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3175,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3200,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3225,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3250,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3500,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3550,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3600,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3650,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3700,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3750,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3800,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3850,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3900,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3950,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4150,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4175,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4200,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4225,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4000,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4050,325,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5375,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(5000,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(4650,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(4250,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(4700,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(5050,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(5425,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(5600,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5575,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5550,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5525,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5500,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5475,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5450,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5350,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5325,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5300,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5275,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5250,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5225,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5200,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5175,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5150,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5100,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5075,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4975,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4950,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4925,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4900,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4875,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4850,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4825,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4800,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4775,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4750,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4725,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4625,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4600,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4575,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4550,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4525,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4475,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4450,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4400,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4375,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4350,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4325,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4300,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4275,275,"back_fence_2"));
      Player.ResetPlayer(25,300);
      Mario.instEnemies.push(new Lakitu(25,15));
      Mario.instEnemies.push(new Lakitu(75,20));
      Mario.instEnemies.push(new Lakitu(125,25));
      Mario.instEnemies.push(new Lakitu(175,30));
      Mario.instEnemies.push(new PPlant(300,275));
      Mario.instEnemies.push(new PPlant(1825,200));
      Mario.instObjects.push(new Finish(5700,325));
      Mario.layerWall.addChild(AddGraphic(75,325,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(225,275,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(400,300,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(825,300,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(1000,325,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(1225,300,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(1900,300,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(2875,300,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(3100,300,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(4175,275,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(5800,300,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(5925,275,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(6000,300,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(6075,300,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(5725,325,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(5875,325,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(6200,325,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(6300,300,"back_tree_2"));
      Mario.layerWall.addChild(AddGraphic(6300,325,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(6075,325,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(6000,325,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(5925,300,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(5800,325,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(4175,300,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(4175,325,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(3100,325,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(2875,325,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(1900,325,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(1225,325,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(825,325,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(400,325,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(225,300,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(225,325,"back_tree_1"));
      Mario.layerWall.addChild(AddGraphic(5925,325,"back_tree_1"));
      Mario.instObjects.push(new Coin(1350,275));
      Mario.instObjects.push(new Coin(1375,275));
      Mario.instObjects.push(new Coin(1425,325));
      Mario.instObjects.push(new Coin(1450,325));
      Mario.instObjects.push(new Coin(1500,275));
      Mario.instObjects.push(new Coin(1525,275));
      Mario.instObjects.push(new Coin(1575,325));
      Mario.instObjects.push(new Coin(1650,275));
      Mario.instObjects.push(new Coin(1625,275));
      Mario.instObjects.push(new Coin(1675,275));
      Mario.instObjects.push(new Coin(1625,300));
      Mario.instObjects.push(new Coin(1625,325));
      Mario.instObjects.push(new Coin(1600,325));
      Mario.instObjects.push(new Coin(1550,325));
      Mario.instObjects.push(new Coin(1550,300));
      Mario.instObjects.push(new Coin(1550,275));
      Mario.instObjects.push(new Coin(1475,275));
      Mario.instObjects.push(new Coin(1475,300));
      Mario.instObjects.push(new Coin(1475,325));
      Mario.instObjects.push(new Coin(1400,275));
      Mario.instObjects.push(new Coin(1400,300));
      Mario.instObjects.push(new Coin(1400,325));
      Mario.instObjects.push(new Coin(3600,100));
      Mario.instObjects.push(new Coin(3625,75));
      Mario.instObjects.push(new Coin(3650,75));
      Mario.instObjects.push(new Coin(3650,100));
      Mario.instObjects.push(new Coin(3625,100));
      Mario.instObjects.push(new Coin(3600,75));
      Mario.instObjects.push(new Coin(3675,100));
      Mario.instObjects.push(new Coin(3675,75));
      Mario.instObjects.push(new Coin(3700,75));
      Mario.instObjects.push(new Coin(3725,75));
      Mario.instObjects.push(new Coin(3750,75));
      Mario.instObjects.push(new Coin(3750,100));
      Mario.instObjects.push(new Coin(3750,125));
      Mario.instObjects.push(new Coin(3700,125));
      Mario.instObjects.push(new Coin(3725,125));
      Mario.instObjects.push(new Coin(3725,100));
      Mario.instObjects.push(new Coin(3700,100));
      Mario.instObjects.push(new Coin(3775,75));
      Mario.instObjects.push(new Coin(3775,100));
      Mario.instObjects.push(new Coin(3800,100));
      Mario.instObjects.push(new Coin(3825,100));
      Mario.instObjects.push(new Coin(3800,75));
      Mario.instObjects.push(new Coin(3800,125));
      Mario.instObjects.push(new Coin(3800,150));
      Mario.instObjects.push(new Coin(3825,150));
      Mario.instObjects.push(new Coin(3825,125));
      Mario.instObjects.push(new Coin(3825,75));
      Mario.instObjects.push(new Coin(3850,150));
      Mario.instObjects.push(new Coin(3850,125));
      Mario.instObjects.push(new Coin(3850,100));
      Mario.instObjects.push(new Coin(3850,75));
      Mario.instObjects.push(new Coin(3875,75));
      Mario.instObjects.push(new Coin(3875,100));
      Mario.instObjects.push(new Coin(3900,100));
      Mario.instObjects.push(new Coin(3900,75));
      Mario.instObjects.push(new Coin(3900,125));
      Mario.instObjects.push(new Coin(3900,150));
      Mario.instObjects.push(new Coin(3925,150));
      Mario.instObjects.push(new Coin(3925,125));
      Mario.instObjects.push(new Coin(3925,100));
      Mario.instObjects.push(new Coin(3925,75));
      Mario.instObjects.push(new Coin(3950,75));
      Mario.instObjects.push(new Coin(3950,100));
      Mario.instObjects.push(new Coin(3950,125));
      Mario.instObjects.push(new Coin(3950,150));
      Mario.instObjects.push(new Coin(3925,175));
      Mario.instObjects.push(new Coin(4025,200));
      Mario.instObjects.push(new Coin(4025,175));
      Mario.instObjects.push(new Coin(4025,150));
      Mario.instObjects.push(new Coin(4000,150));
      Mario.instObjects.push(new Coin(4000,125));
      Mario.instObjects.push(new Coin(4000,100));
      Mario.instObjects.push(new Coin(3975,100));
      Mario.instObjects.push(new Coin(4000,75));
      Mario.instObjects.push(new Coin(4025,75));
      Mario.instObjects.push(new Coin(4050,75));
      Mario.instObjects.push(new Coin(4050,100));
      Mario.instObjects.push(new Coin(4050,125));
      Mario.instObjects.push(new Coin(4050,150));
      Mario.instObjects.push(new Coin(4025,125));
      Mario.instObjects.push(new Coin(4025,100));
      Mario.instObjects.push(new Coin(3975,75));
      Mario.instObjects.push(new Coin(4075,100));
      Mario.instObjects.push(new Coin(4075,75));
      Mario.instObjects.push(new Coin(4100,75));
      Mario.instObjects.push(new Coin(4100,100));
      Mario.instObjects.push(new Coin(4100,125));
      Mario.instObjects.push(new Coin(4100,150));
      Mario.instObjects.push(new Coin(4125,150));
      Mario.instObjects.push(new Coin(4125,125));
      Mario.instObjects.push(new Coin(4125,100));
      Mario.instObjects.push(new Coin(4125,75));
      Mario.instObjects.push(new Coin(4125,175));
      Mario.instObjects.push(new Coin(4125,200));
      Mario.instObjects.push(new Coin(4125,225));
      Mario.instEffects.push(new Back(5));
   }
}
