package objects.levelMakes
{
   import objects.*;
   
   public function MakeLevel1_4() : void
   {
      Mario.levelGenre = 3;
      Mario.musika = 2;
      Mario.level[0] = "       ABAB         ABABABABABC AB          ABC              DABABABABD    ABAB                     ABABABD            CABC  DABABABAB                       DABABABABABABABABAH";
      Mario.level[1] = "        AB                  D ABC             AB                CAB DABCABAB  D                                         CDABDAB                              AB                H";
      Mario.level[2] = "                                                                                                                                                             CD                H";
      Mario.level[3] = "                                                                                                                                                             AB                H";
      Mario.level[4] = "                                                                                                                                                             DC                H";
      Mario.level[5] = "               01                                                                                                                                            AB                H";
      Mario.level[6] = "              EFFG                                                                                                                                                             H";
      Mario.level[7] = "              HIIJ                   EFG                              EFG                                                                                                      H";
      Mario.level[8] = "              HIIJ                   HIJ  EFG                    EFG  HIJ                             EFG             EFG                                                      H";
      Mario.level[9] = "FFFFFFFFFFGP  HIIJ   COOOOOOOOOOOC   HIJ  HIJ COOOOOOOOOOOOOOOOD HIJ  HIJ                            MHIJ  ABABCABAB  HIJM                                 MEFGOOOOOOOOOOOOOOOOH";
      Mario.level[10] = "IIIIIIIIIIJ   HIIJ                   HIJ  HIJ                    HIJ  HIJ                           MMHIJ             HIJMM        01                     MMHIJ                H";
      Mario.level[11] = "IIIIIIIIIIJ   HIIJ                   HIJ  HIJ                    HIJ  HIJ        01     01         MMMHIJ             HIJMMM       23     01             MMMHIJ                H";
      Mario.level[12] = "IIIIIIIIIILFFFKIIJ                   HIJ  HIJ                    HIJ  HIJ      EFFFFFFFFFFFG    EFFFFFKIJ             HILFFFFFFFFFFFFFG   23   EFFFFFFFFFFFFKIJ                H";
      Mario.level[13] = "IIIIIIIIIIIIIIIIIJ                   HIJ  HIJ                    HIJ  HIJ      HIIIIIIIIIIIJ    HIIIIIIIJ             HIIIIIIIIIIIIIIIJ   23   HIIIIIIIIIIIIIIJ                H";
      Mario.level[14] = "IIIIIIIIIIIIIIIIIJ                   HIJ  HIJ                    HIJ  HIJ      HIIIIIIIIIIIJ    HIIIIIIIJ             HIIIIIIIIIIIIIIIJ   23   HIIIIIIIIIIIIIIJ                H";
      Mario.levelWid = Mario.level[0].length;
      Mario.levelHei = Mario.level.length;
      Mario.drawLevel();
      Mario.Hud.Time = 320;
      Player.ResetPlayer(Mario.checkPoint == 3 ? 3600 : 25,175);
      Mario.instEnemies.push(new Bowser(4250,200,3975,3,3,0,0,0));
      Mario.instBlocks.push(new Brick(3625,200));
      Mario.instBlocks.push(new Brick(3675,200));
      Mario.instBlocks.push(new Brick(3700,200));
      Mario.instBlocks.push(new Brick(3750,200));
      Mario.instBlocks.push(new Brick(2575,75));
      Mario.instBlocks.push(new Brick(2975,75));
      Mario.instBlocks.push(new Brick(2125,200));
      Mario.instBlocks.push(new Brick(1200,125));
      Mario.instBlocks.push(new Brick(1500,125));
      Mario.instBlocks.push(new Brick(200,125));
      Mario.instObjects.push(new Coin(775,125));
      Mario.instObjects.push(new Coin(750,125));
      Mario.instObjects.push(new Coin(100,75));
      Mario.instObjects.push(new Coin(200,75));
      Mario.instObjects.push(new Coin(950,125));
      Mario.instObjects.push(new Coin(950,150));
      Mario.instObjects.push(new Coin(1350,175));
      Mario.instObjects.push(new Coin(1375,175));
      Mario.instObjects.push(new Coin(1750,100));
      Mario.instObjects.push(new Coin(1775,100));
      Mario.instObjects.push(new Coin(1800,100));
      Mario.instObjects.push(new Coin(2175,200));
      Mario.instObjects.push(new Coin(2075,200));
      Mario.instObjects.push(new Coin(2500,225));
      Mario.instObjects.push(new Coin(2475,250));
      Mario.instObjects.push(new Coin(2525,200));
      Mario.instObjects.push(new Coin(2475,225));
      Mario.instObjects.push(new Coin(2500,200));
      Mario.instObjects.push(new Coin(3025,200));
      Mario.instObjects.push(new Coin(3050,200));
      Mario.instObjects.push(new Coin(3050,225));
      Mario.instObjects.push(new Coin(3075,225));
      Mario.instObjects.push(new Coin(3075,250));
      Mario.instBlocks.push(new Bonus(2725,125,0));
      Mario.instBlocks.push(new Bonus(2825,125,1));
      Mario.instBlocks.push(new Bonus(1475,150,1));
      Mario.instBlocks.push(new Bonus(1225,150,0));
      Mario.instBlocks.push(new Bonus(575,125,2));
      Mario.instBlocks.push(new Bonus(75,125,1));
      Mario.instBlocks.push(new Bonus(100,125,0));
      Mario.instEnemies.push(new PPlant(3450,250));
      Mario.instEnemies.push(new PPlant(3275,225));
      Mario.instEnemies.push(new PPlant(2200,250));
      Mario.instEnemies.push(new PPlant(2025,250));
      Mario.instEnemies.push(new PPlant(375,100));
      Mario.instBlocks.push(new Bonus(3900,125,4,true));
      Mario.instObjects.push(new Coin(3650,150));
      Mario.instObjects.push(new Coin(3675,150));
      Mario.instObjects.push(new Coin(3700,150));
      Mario.instObjects.push(new Coin(3725,150));
      Mario.instObjects.push(new Coin(3675,100));
      Mario.instObjects.push(new Coin(3700,100));
      Mario.instBlocks.push(new BrickMulti(3650,200));
      Mario.instBlocks.push(new BrickMulti(3725,200));
      Mario.instEnemies.push(new Goomba(2825,200));
      Mario.instEnemies.push(new Goomba(1550,200));
      Mario.instEnemies.push(new Goomba(1500,200));
      Mario.instEnemies.push(new Goomba(1450,200));
      Mario.instEnemies.push(new Goomba(750,200));
      Mario.instEnemies.push(new TroopaRed(700,200));
      Mario.instEnemies.push(new TroopaGreen(1375,200));
      Mario.instEnemies.push(new JumperThrower(1850,350,-9,0.5,100,1,0));
      Mario.instEnemies.push(new JumperThrower(1925,350,-9,0.5,100,1,0));
      Mario.instEffects.push(new Back(3));
   }
}
