package objects.levelMakes
{
   import objects.*;
   
   public function MakeLevel2_3() : void
   {
      Mario.levelGenre = 0;
      Mario.musika = 0;
      Mario.level[0] = "                                                                                                                                                                                                                                                                                                                                      ";
      Mario.level[1] = "                                                                                                                                                                                                                                                                                                                                      ";
      Mario.level[2] = "                                                                                                                                                                                                                                                                                                                                      ";
      Mario.level[3] = "                                                                                                                                                                                                                                                                                                                                      ";
      Mario.level[4] = "                                                                                                                                                                                                                                                                                                                                      ";
      Mario.level[5] = "                                                                                                                                                                                                                                                                                                                                      ";
      Mario.level[6] = "                                                                                                                MQQQ01QQQQM                                                                                                                                                                                                           ";
      Mario.level[7] = "                                                     01               01                                            23                                                                                                                                                                                                                ";
      Mario.level[8] = "                                                     23               23                            MQQQQQQQQM      23                                                   01                                                                                                                                                           ";
      Mario.level[9] = " MQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQM     MQQQQQQQQ23QQQQQQQQQQQQQQQ23QQQQQQQQM                                   23       MQQQQQQQQQM                          MQQQQQQ23QQQQQQQQQQQQQQQQQQQQQQQQQQQM                                                                                                                               ";
      Mario.level[10] = "                                                     23               23                                            23                                                   23                                                                                                                                                           ";
      Mario.level[11] = "                                                     23               23           MQQQQQQQQQQQQQQM                 23                    MQQQQQQQQQQQQQQQQQQQQM         23                                                                                                                                                           ";
      Mario.level[12] = "                                                     23               23                                            23                                                   23                                MQQQQQQQQQQQQQQQQQQQQQQQQQQQM      MQQQQQQQQM    MQQQQQQQQQQM        MQQQQQQM        MQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQM";
      Mario.level[13] = "                                                     23               23                                            23                                                   23                                                                                                                                                           ";
      Mario.level[14] = "                                                     23               23                                            23                                                   23                                                                                                                                                           ";
      Mario.levelWid = Mario.level[0].length;
      Mario.levelHei = Mario.level.length;
      Mario.drawLevel();
      Mario.Hud.Time = 320;
      Mario.instEffects.push(new Cloud(100,175));
      Mario.instEffects.push(new Cloud(775,300));
      Mario.instEffects.push(new Cloud(1375,75));
      Mario.instEffects.push(new Cloud(2150,225));
      Mario.instEffects.push(new Cloud(2750,50));
      Mario.instEffects.push(new Cloud(3725,100));
      Mario.instEffects.push(new Cloud(4625,50));
      Mario.instEffects.push(new Cloud(5150,150));
      Mario.instEffects.push(new Cloud(5650,25));
      Mario.instEffects.push(new Cloud(6300,200));
      Mario.instEffects.push(new Cloud(6625,50));
      Mario.instEffects.push(new Cloud(7050,50));
      Mario.instEffects.push(new Cloud(7375,175));
      Mario.instEffects.push(new Cloud(7800,50));
      Mario.instEffects.push(new Background(5550,250,"back_clouds_3",0.37));
      Mario.instEffects.push(new Background(1925,75,"back_clouds_3",0.36));
      Mario.instEffects.push(new Background(7775,250,"back_clouds_2",0.35));
      Mario.instEffects.push(new Background(7875,50,"back_clouds_1",0.32));
      Mario.instEffects.push(new Background(7550,75,"back_clouds_3",0.32));
      Mario.instEffects.push(new Background(375,25,"back_clouds_1",0.32));
      Mario.instEffects.push(new Background(700,75,"back_clouds_3",0.32));
      Mario.instEffects.push(new Background(375,25,"back_clouds_1",0.32));
      Mario.instEffects.push(new Background(3200,25,"back_clouds_3",0.31));
      Mario.instEffects.push(new Background(5750,175,"back_clouds_2",0.28));
      Mario.instEffects.push(new Background(1700,25,"back_clouds_1",0.25));
      Mario.instEffects.push(new Background(4825,225,"back_clouds_2",0.25));
      Mario.instEffects.push(new Background(6850,0,"back_clouds_2",0.25));
      Mario.instEffects.push(new Background(4225,0,"back_clouds_2",0.21));
      Mario.instEffects.push(new Background(1375,225,"back_clouds_3",0.2));
      Mario.instEffects.push(new Background(5300,0,"back_clouds_1",0.18));
      Mario.instEffects.push(new Background(2950,175,"back_clouds_1",0.17));
      Mario.instEffects.push(new Background(2225,0,"back_clouds_2",0.15));
      Mario.instEffects.push(new Background(3450,125,"back_clouds_2",0.15));
      Mario.instEffects.push(new Background(4100,250,"back_clouds_3",0.14));
      Mario.instEffects.push(new Background(975,175,"back_clouds_1",0.14));
      Mario.instEffects.push(new Background(6100,75,"back_clouds_3",0.14));
      Mario.instEffects.push(new Background(100,50,"back_clouds_3",0.14));
      Mario.instEffects.push(new Background(3900,50,"back_clouds_1",0.12));
      Mario.instEffects.push(new Background(300,200,"back_clouds_3",0.1));
      Mario.instEffects.push(new Background(2450,275,"back_clouds_3",0.1));
      Mario.instEffects.push(new Background(7125,250,"back_clouds_3",0.1));
      Mario.instEffects.push(new Background(4875,50,"back_clouds_3",0.1));
      Mario.instEffects.push(new Background(525,175,"back_clouds_2",0.09));
      Mario.instEffects.push(new Background(1075,25,"back_clouds_2",0.09));
      Mario.instEffects.push(new Background(6650,225,"back_clouds_1",0.05));
      Mario.layerWall.addChild(AddGraphic(225,200,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(700,200,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(925,200,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(1225,200,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(1425,200,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(1900,200,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(2450,250,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(2650,175,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(2900,125,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(3375,200,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(3550,250,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(3875,250,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(4700,200,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(4850,200,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(5275,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(5675,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(6050,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(6150,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(6550,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(7000,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(7325,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(7475,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(7675,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(7750,275,"back_fence_3"));
      Mario.layerWall.addChild(AddGraphic(7700,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(7525,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(7350,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(7175,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(6825,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(6375,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(6100,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(5950,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(5500,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(5175,275,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(4750,200,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(4525,200,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(4125,200,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(3725,250,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(3450,250,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(3225,200,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(2800,125,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(2500,175,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(2275,250,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(1675,200,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(1150,200,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(825,200,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(575,200,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(150,200,"back_fence_1"));
      Mario.layerWall.addChild(AddGraphic(175,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(200,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(600,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(625,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(650,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(675,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(850,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(875,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(900,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1175,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1200,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1375,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1400,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1700,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1725,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1800,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1825,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1850,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(1875,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2300,250,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2325,250,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2350,250,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2375,250,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2400,250,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2425,250,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2625,175,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2600,175,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2575,175,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2550,175,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2525,175,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2825,125,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2850,125,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(2875,125,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3250,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3275,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3300,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3325,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3350,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3475,250,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3500,250,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3525,250,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3750,250,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3850,250,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3825,250,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3800,250,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(3775,250,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4150,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4175,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4200,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4550,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4575,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4600,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4625,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4650,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4675,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4775,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4800,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(4825,200,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5200,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5225,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5250,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5525,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5550,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5575,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5600,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5625,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5650,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6025,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6000,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(5975,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6125,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6400,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6425,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6450,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6475,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6500,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6525,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6850,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6875,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6900,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6925,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6950,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(6975,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7725,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7650,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7625,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7600,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7575,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7550,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7400,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7450,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7425,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7375,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7300,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7275,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7250,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7225,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7200,275,"back_fence_2"));
      Mario.layerWall.addChild(AddGraphic(7400,25,"back_castle"));
      Player.ResetPlayer(75,175);
      Mario.instObjects.push(new Finish(7300,275));
      Mario.instBlocks.push(new Brick(250,125));
      Mario.instBlocks.push(new Brick(325,125));
      Mario.instBlocks.push(new Brick(475,125));
      Mario.instBlocks.push(new Brick(1925,125));
      Mario.instBlocks.push(new Brick(1175,125));
      Mario.instBlocks.push(new Brick(2200,150));
      Mario.instBlocks.push(new Brick(2550,125));
      Mario.instBlocks.push(new Brick(2150,150));
      Mario.instBlocks.push(new Brick(3225,125));
      Mario.instBlocks.push(new Brick(3250,125));
      Mario.instBlocks.push(new Brick(3525,175));
      Mario.instBlocks.push(new Brick(3825,175));
      Mario.instBlocks.push(new Brick(4375,150));
      Mario.instBlocks.push(new Brick(4400,150));
      Mario.instBlocks.push(new Brick(4525,125));
      Mario.instBlocks.push(new Brick(4675,150));
      Mario.instBlocks.push(new Brick(4700,150));
      Mario.instBlocks.push(new Brick(6050,200));
      Mario.instBlocks.push(new Brick(6450,200));
      Mario.instBlocks.push(new Bonus(6425,200,1));
      Mario.instBlocks.push(new Bonus(6075,200,1));
      Mario.instBlocks.push(new Bonus(5300,200,1));
      Mario.instBlocks.push(new Bonus(4550,125,1));
      Mario.instBlocks.push(new Bonus(4350,150,1));
      Mario.instBlocks.push(new Bonus(3625,150,1));
      Mario.instBlocks.push(new Bonus(3725,150,1));
      Mario.instBlocks.push(new Bonus(3200,125,1));
      Mario.instBlocks.push(new Bonus(3275,125,1));
      Mario.instBlocks.push(new Bonus(2850,50,1));
      Mario.instBlocks.push(new Bonus(2675,125,1));
      Mario.instBlocks.push(new Bonus(1550,125,1));
      Mario.instBlocks.push(new Bonus(500,125,1));
      Mario.instBlocks.push(new Bonus(525,125,1));
      Mario.instBlocks.push(new Bonus(300,125,1));
      Mario.instBlocks.push(new Bonus(275,125,1));
      Mario.instBlocks.push(new BrickMulti(550,125));
      Mario.instBlocks.push(new BrickMulti(1525,125));
      Mario.instBlocks.push(new BrickMulti(2175,150));
      Mario.instBlocks.push(new BrickMulti(2975,50));
      Mario.instBlocks.push(new BrickMulti(3550,150));
      Mario.instBlocks.push(new BrickMulti(3800,150));
      Mario.instBlocks.push(new BrickMulti(4500,125));
      Mario.instBlocks.push(new Bonus(4575,125,2));
      Mario.instBlocks.push(new Bonus(4725,150,3));
      Mario.instBlocks.push(new Bonus(5475,200,3));
      Mario.instObjects.push(new Coin(5300,150));
      Mario.instObjects.push(new Coin(5300,125));
      Mario.instObjects.push(new Coin(5475,125));
      Mario.instObjects.push(new Coin(5475,150));
      Mario.instObjects.push(new Coin(5400,200));
      Mario.instObjects.push(new Coin(5375,200));
      Mario.instObjects.push(new Coin(4700,100));
      Mario.instObjects.push(new Coin(4375,100));
      Mario.instObjects.push(new Coin(4525,50));
      Mario.instObjects.push(new Coin(4550,50));
      Mario.instObjects.push(new Coin(4550,25));
      Mario.instObjects.push(new Coin(4525,25));
      Mario.instObjects.push(new Coin(3725,75));
      Mario.instObjects.push(new Coin(3800,75));
      Mario.instObjects.push(new Coin(3825,100));
      Mario.instObjects.push(new Coin(3625,75));
      Mario.instObjects.push(new Coin(3550,75));
      Mario.instObjects.push(new Coin(3525,100));
      Mario.instObjects.push(new Coin(3225,50));
      Mario.instObjects.push(new Coin(3250,50));
      Mario.instObjects.push(new Coin(2600,75));
      Mario.instObjects.push(new Coin(2625,75));
      Mario.instObjects.push(new Coin(2850,100));
      Mario.instObjects.push(new Coin(2975,100));
      Mario.instObjects.push(new Coin(2350,175));
      Mario.instObjects.push(new Coin(2375,175));
      Mario.instObjects.push(new Coin(2325,175));
      Mario.instObjects.push(new Coin(1650,125));
      Mario.instObjects.push(new Coin(1425,125));
      Mario.instObjects.push(new Coin(400,175));
      Mario.instObjects.push(new Coin(375,175));
      Mario.instObjects.push(new Coin(425,175));
      Mario.instObjects.push(new Coin(300,75));
      Mario.instObjects.push(new Coin(275,75));
      Mario.instObjects.push(new Coin(500,75));
      Mario.instObjects.push(new Coin(525,75));
      Mario.instBlocks.push(new Bonus(1175,25,4,true));
      Mario.instEnemies.push(new PPlant(1325,150));
      Mario.instEnemies.push(new PPlant(1750,150));
      Mario.instEnemies.push(new PPlant(2900,125));
      Mario.instEnemies.push(new PPlant(4225,175));
      Mario.instObjects.push(new ElevatorFall(6675,300,50,"elevator_2"));
      Mario.instObjects.push(new ElevatorFall(7075,300,50,"elevator_2"));
      Mario.instObjects.push(new ElevatorFall(5850,300,50,"elevator_2"));
      Mario.instEnemies.push(new PStatic(750,200));
      Mario.instEnemies.push(new PStatic(725,200));
      Mario.instEnemies.push(new PStatic(1300,200));
      Mario.instEnemies.push(new PStatic(1375,200));
      Mario.instEnemies.push(new PStatic(1725,200));
      Mario.instEnemies.push(new PStatic(1800,200));
      Mario.instEnemies.push(new PStatic(2200,250));
      Mario.instEnemies.push(new PStatic(2225,250));
      Mario.instEnemies.push(new PStatic(2400,250));
      Mario.instEnemies.push(new PStatic(2600,175));
      Mario.instEnemies.push(new PStatic(3000,125));
      Mario.instEnemies.push(new PStatic(3175,200));
      Mario.instEnemies.push(new PStatic(3650,250));
      Mario.instEnemies.push(new PStatic(3700,250));
      Mario.instEnemies.push(new PStatic(3950,250));
      Mario.instEnemies.push(new PStatic(4100,200));
      Mario.instEnemies.push(new PStatic(4200,200));
      Mario.instEnemies.push(new PStatic(4450,200));
      Mario.instEnemies.push(new PStatic(4875,200));
      Mario.instEnemies.push(new PStatic(5150,275));
      Mario.instEnemies.push(new PStatic(5175,275));
      Mario.instEnemies.push(new PStatic(5325,275));
      Mario.instEnemies.push(new PStatic(5675,275));
      Mario.instEnemies.push(new PStatic(5575,275));
      Mario.instEnemies.push(new PStatic(6000,275));
      Mario.instEnemies.push(new PStatic(6400,275));
      Mario.instEnemies.push(new PStatic(6500,275));
      Mario.instEnemies.push(new PStatic(6900,275));
      Mario.instEnemies.push(new FlyRed(7025,200));
      Mario.instEnemies.push(new FlyRed(7150,150));
      Mario.instEnemies.push(new FlyRed(6750,175));
      Mario.instEnemies.push(new FlyRed(6625,200));
      Mario.instEnemies.push(new FlyRed(6250,175));
      Mario.instEnemies.push(new FlyRed(5925,200));
      Mario.instEnemies.push(new FlyRed(5800,150));
      Mario.instEnemies.push(new FlyRed(1025,175));
      Mario.instEnemies.push(new FlyGreen(550,75));
      Mario.instEnemies.push(new FlyGreen(325,75));
      Mario.instEnemies.push(new FlyGreen(1550,75));
      Mario.instEnemies.push(new FlyGreen(2175,100));
      Mario.instEnemies.push(new FlyGreen(4525,75));
      Mario.instEnemies.push(new FlyGreen(5550,200));
      Mario.instEnemies.push(new FlyGreen(6150,100));
      Mario.instEffects.push(new Back(4));
   }
}
