package objects.levelMakes
{
   import objects.*;
   
   public function MakeLevel3_2() : void
   {
      Mario.levelGenre = 1;
      Mario.musika = 1;
      Mario.level[0] = "                                                                                                                                                                                                                                                                          ";
      Mario.level[1] = "                                                                                                                                                                                                                                                                          ";
      Mario.level[2] = "                                                                                                                                                                                                                                                                          ";
      Mario.level[3] = "                                                                                                                                                                                                                                                                          ";
      Mario.level[4] = "                                                     N                                                                                                                                                                                                                    ";
      Mario.level[5] = "                                                     N                                                                                                                                                                                                                    ";
      Mario.level[6] = "                                                    NN                                                                                                                                                                                                                    ";
      Mario.level[7] = "                                                    cde                                                                                                                                                                                                                   ";
      Mario.level[8] = "                                                   Nfgh                                                         cde                N   N   N   N   N   N             01                 01                                                                                ";
      Mario.level[9] = "                                                  cefghN                                                        ijk                R   R   R   R   R   R             23                 23                                                                                ";
      Mario.level[10] = "                                                 NfhfghN                  cddde            cddde                                   R   R   R   R   R   R             23                 23                                                                                ";
      Mario.level[11] = "                                                 Nfhfghce                 fgggh            fgggh                                   R   R   R   R   R   R             23                 23                                                                                ";
      Mario.level[12] = "     N  N  NN     NN  N  N  N  N    NN    NN    cefhfghfhN               Nfgggh            fgggh                                   R   R   R   R   R   R             23                 23                                                                                ";
      Mario.level[13] = "   cddddddddde   cdddddddddddddde  cdde  cdde   fhfhfghfhcde           cdefgggh            fgggh                                   R   R   R   R   R   R             23                 23                 cddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddde";
      Mario.level[14] = "   fggggggggghQQQfgggggggggggggghQQfgghQQfgghQQQfhfhfghfhfghcdddddddddefghfgggh            fgggh                                   R   R   R   R   R   R             23                 23                 fgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggh";
      Mario.levelWid = Mario.level[0].length;
      Mario.levelHei = Mario.level.length;
      Mario.Hud.Time = 320;
      Mario.layerWall.addChild(AddGraphic(5625,225,"back_crystal_3"));
      Mario.layerWall.addChild(AddGraphic(5150,225,"back_crystal_3"));
      Mario.layerWall.addChild(AddGraphic(4875,300,"back_crystal_1"));
      Mario.layerWall.addChild(AddGraphic(4225,275,"back_crystal_1"));
      Mario.layerWall.addChild(AddGraphic(3675,200,"back_crystal_2"));
      Mario.layerWall.addChild(AddGraphic(2725,200,"back_crystal_2"));
      Mario.layerWall.addChild(AddGraphic(2000,275,"back_crystal_1"));
      Mario.layerWall.addChild(AddGraphic(425,225,"back_crystal_1"));
      Mario.layerWall.addChild(AddGraphic(125,225,"back_crystal_3"));
      Mario.layerWall.addChild(AddGraphic(625,225,"back_crystal_3"));
      Mario.layerWall.addChild(AddGraphic(1475,175,"back_crystal_2"));
      Mario.layerWall.addChild(AddGraphic(6025,150,"back_crystal_2"));
      Mario.drawLevel();
      Player.ResetPlayer(75,275);
      Mario.instEnemies.push(new PStatic(125,275));
      Mario.instEnemies.push(new PStatic(200,275));
      Mario.instEnemies.push(new PStatic(300,275));
      Mario.instEnemies.push(new PStatic(275,275));
      Mario.instEnemies.push(new PStatic(450,275));
      Mario.instEnemies.push(new PStatic(475,275));
      Mario.instEnemies.push(new PStatic(550,275));
      Mario.instEnemies.push(new PStatic(625,275));
      Mario.instEnemies.push(new PStatic(700,275));
      Mario.instEnemies.push(new PStatic(775,275));
      Mario.instEnemies.push(new PStatic(925,275));
      Mario.instEnemies.push(new PStatic(900,275));
      Mario.instEnemies.push(new PStatic(1075,275));
      Mario.instEnemies.push(new PStatic(1050,275));
      Mario.instEnemies.push(new PStatic(1225,225));
      Mario.instEnemies.push(new PStatic(1275,175));
      Mario.instEnemies.push(new PStatic(1325,75));
      Mario.instEnemies.push(new PStatic(1375,200));
      Mario.instEnemies.push(new PStatic(1425,275));
      Mario.instEnemies.push(new PStatic(3275,175));
      Mario.instEnemies.push(new PStatic(3375,175));
      Mario.instEnemies.push(new PStatic(3475,175));
      Mario.instEnemies.push(new PStatic(3575,175));
      Mario.instEnemies.push(new PStatic(3675,175));
      Mario.instEnemies.push(new PStatic(3775,175));
      Mario.instEnemies.push(new PStatic(4150,175));
      Mario.instEnemies.push(new PStatic(4125,175));
      Mario.instEnemies.push(new PStatic(4625,175));
      Mario.instEnemies.push(new PStatic(4600,175));
      Mario.instEnemies.push(new PPlant(4600,175));
      Mario.instEnemies.push(new PPlant(4125,175));
      Mario.instObjects.push(new ElevatorFall(2025,250,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(2200,250,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(2125,250,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(2100,250,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(2675,250,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(2600,300,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(2525,350,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(2750,200,50,"elevator_2"));
      Mario.instObjects.push(new ElevatorFall(2875,200,50,"elevator_2"));
      Mario.instObjects.push(new ElevatorFall(3025,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3100,350,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3175,350,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3250,350,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3250,275,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3250,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3325,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3425,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3525,250,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3625,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3725,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3800,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3825,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3850,250,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3875,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3900,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3925,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3950,250,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(3975,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4000,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4025,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4050,250,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4075,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4100,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4175,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4200,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4225,250,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4250,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4275,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4300,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4325,250,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4350,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4375,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4400,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4425,250,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4450,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4475,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4500,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4525,250,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4550,225,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4575,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4650,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4725,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4800,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4875,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(4950,200,25,"elevator_1"));
      Mario.instObjects.push(new ElevatorFall(5025,200,25,"elevator_1"));
      Mario.instObjects.push(new Finish(6050,300));
      Mario.instEnemies.push(new Spiny(5325,300));
      Mario.instBlocks.push(new Bonus(5550,200,2));
      Mario.instBlocks.push(new Bonus(5400,200,3));
      Mario.instBlocks.push(new Bonus(5700,200,3));
      Mario.instBlocks.push(new Bonus(5850,200,3));
      Mario.instBlocks.push(new Bonus(5250,200,3));
      Mario.instBlocks.push(new Bonus(5175,200,3));
      Mario.instBlocks.push(new Bonus(5325,200,3));
      Mario.instBlocks.push(new Bonus(5475,200,3));
      Mario.instBlocks.push(new Bonus(5625,200,3));
      Mario.instBlocks.push(new Bonus(5775,200,4));
      Mario.instObjects.push(new Coin(5175,150));
      Mario.instObjects.push(new Coin(5175,125));
      Mario.instObjects.push(new Coin(5175,100));
      Mario.instObjects.push(new Coin(5175,175));
      Mario.instObjects.push(new Coin(5250,175));
      Mario.instObjects.push(new Coin(5250,150));
      Mario.instObjects.push(new Coin(5250,125));
      Mario.instObjects.push(new Coin(5250,100));
      Mario.instObjects.push(new Coin(5325,100));
      Mario.instObjects.push(new Coin(5325,125));
      Mario.instObjects.push(new Coin(5325,150));
      Mario.instObjects.push(new Coin(5325,175));
      Mario.instObjects.push(new Coin(5400,175));
      Mario.instObjects.push(new Coin(5400,150));
      Mario.instObjects.push(new Coin(5400,125));
      Mario.instObjects.push(new Coin(5400,100));
      Mario.instObjects.push(new Coin(5475,100));
      Mario.instObjects.push(new Coin(5475,125));
      Mario.instObjects.push(new Coin(5475,150));
      Mario.instObjects.push(new Coin(5475,175));
      Mario.instObjects.push(new Coin(5550,175));
      Mario.instObjects.push(new Coin(5550,150));
      Mario.instObjects.push(new Coin(5550,125));
      Mario.instObjects.push(new Coin(5550,100));
      Mario.instObjects.push(new Coin(5625,100));
      Mario.instObjects.push(new Coin(5625,125));
      Mario.instObjects.push(new Coin(5625,150));
      Mario.instObjects.push(new Coin(5625,175));
      Mario.instObjects.push(new Coin(5700,175));
      Mario.instObjects.push(new Coin(5700,150));
      Mario.instObjects.push(new Coin(5700,125));
      Mario.instObjects.push(new Coin(5700,100));
      Mario.instObjects.push(new Coin(5775,100));
      Mario.instObjects.push(new Coin(5775,125));
      Mario.instObjects.push(new Coin(5775,150));
      Mario.instObjects.push(new Coin(5775,175));
      Mario.instObjects.push(new Coin(5850,175));
      Mario.instObjects.push(new Coin(5850,150));
      Mario.instObjects.push(new Coin(5850,125));
      Mario.instObjects.push(new Coin(5850,100));
      Mario.instBlocks.push(new Bonus(5150,75,4,true));
      Mario.instEnemies.push(new Goomba(1675,325));
      Mario.instEnemies.push(new Goomba(1650,325));
      Mario.instEnemies.push(new Goomba(1625,325));
      Mario.instEnemies.push(new Goomba(1600,325));
      Mario.instEnemies.push(new Goomba(1575,325));
      Mario.instEnemies.push(new Goomba(1525,325));
      Mario.instEnemies.push(new Goomba(1725,325));
      Mario.instEnemies.push(new Goomba(1750,325));
      Mario.instEnemies.push(new Goomba(1500,325));
      Mario.instEnemies.push(new Spiny(1550,325));
      Mario.instEnemies.push(new Spiny(1700,325));
      Mario.instObjects.push(new Coin(1275,150));
      Mario.instObjects.push(new Coin(1225,200));
      Mario.instObjects.push(new Coin(1225,175));
      Mario.instObjects.push(new Coin(1275,125));
      Mario.instObjects.push(new Coin(1325,25));
      Mario.instObjects.push(new Coin(1325,50));
      Mario.instObjects.push(new Coin(1375,175));
      Mario.instObjects.push(new Coin(1375,150));
      Mario.instObjects.push(new Coin(1425,250));
      Mario.instObjects.push(new Coin(1425,225));
      Mario.instObjects.push(new Coin(1075,250));
      Mario.instObjects.push(new Coin(1050,250));
      Mario.instObjects.push(new Coin(900,250));
      Mario.instObjects.push(new Coin(925,250));
      Mario.instObjects.push(new Coin(775,250));
      Mario.instObjects.push(new Coin(700,250));
      Mario.instObjects.push(new Coin(625,250));
      Mario.instObjects.push(new Coin(550,250));
      Mario.instObjects.push(new Coin(450,250));
      Mario.instObjects.push(new Coin(475,250));
      Mario.instObjects.push(new Coin(300,250));
      Mario.instObjects.push(new Coin(275,250));
      Mario.instObjects.push(new Coin(200,250));
      Mario.instObjects.push(new Coin(125,250));
      Mario.instEnemies.push(new PStatic(2850,175));
      Mario.instEnemies.push(new PStatic(2825,175));
      Mario.instEnemies.push(new PStatic(2800,175));
      Mario.instObjects.push(new Coin(3275,150));
      Mario.instObjects.push(new Coin(3275,125));
      Mario.instObjects.push(new Coin(3375,125));
      Mario.instObjects.push(new Coin(3375,150));
      Mario.instObjects.push(new Coin(3475,125));
      Mario.instObjects.push(new Coin(3475,150));
      Mario.instObjects.push(new Coin(3575,125));
      Mario.instObjects.push(new Coin(3575,150));
      Mario.instObjects.push(new Coin(3675,125));
      Mario.instObjects.push(new Coin(3675,150));
      Mario.instObjects.push(new Coin(3775,125));
      Mario.instObjects.push(new Coin(3775,150));
      Mario.instObjects.push(new Coin(4125,125));
      Mario.instObjects.push(new Coin(4125,150));
      Mario.instObjects.push(new Coin(4150,150));
      Mario.instObjects.push(new Coin(4150,125));
      Mario.instObjects.push(new Coin(4600,125));
      Mario.instObjects.push(new Coin(4600,150));
      Mario.instObjects.push(new Coin(4625,150));
      Mario.instObjects.push(new Coin(4625,125));
      Mario.instEnemies.push(new Spiny(5525,300));
      Mario.instEnemies.push(new Spiny(5425,300));
      Mario.instEnemies.push(new Spiny(5625,300));
      Mario.instEnemies.push(new Spiny(5725,300));
      Mario.instEnemies.push(new Spiny(5825,300));
      Mario.instEnemies.push(new Spiny(5925,300));
      Mario.instEnemies.push(new Spiny(5225,300));
      Mario.instEnemies.push(new PStatic(2325,225));
      Mario.instEnemies.push(new PStatic(1900,225));
      Mario.instEffects.push(new Back(1));
   }
}
