Generate_Ingame("zzzzzzzzzzzzzzzzzzbbbbbbbbzzzzzzbybbbubbzzzzzzbbbbbbbbzzzzzzbbbbbobbzzzzzzbrbbbibrzzzzzzbbbbbbbuzzzzzzbbbbbbbbzzzzzzbubybbbbzzzzzzbbbbbbbuzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz")
global.l_title="Lil' Going"
global.l_author="Maurice Zarzycki"
global.pathx=50