package submuncher.core.constants {
    import submuncher.ingame.gameObjects.BonusKey;
    import submuncher.ingame.gameObjects.ObjectDetector;

    public class SpriteNames {
        public static const AMMO_1:String = "ammo1";
        public static const AMMO_5:String = "ammo2";
        public static const AMMO_INFINITE:String = "ammo3";
        public static const BARREL:String = "barrel";
        public static const BARRIER_HORIZONTAL_BLUE_0:String = "barrier_horizontal_blue_0";
        public static const BARRIER_HORIZONTAL_BLUE_1:String = "barrier_horizontal_blue_1";
        public static const BARRIER_HORIZONTAL_BLUE_2:String = "barrier_horizontal_blue_2";
        public static const BARRIER_HORIZONTAL_BLUE_3:String = "barrier_horizontal_blue_3";
        public static const BARRIER_HORIZONTAL_BLUE_4:String = "barrier_horizontal_blue_4";
        public static const BARRIER_HORIZONTAL_GRAY_0:String = "barrier_horizontal_gray_0";
        public static const BARRIER_HORIZONTAL_GRAY_1:String = "barrier_horizontal_gray_1";
        public static const BARRIER_HORIZONTAL_GRAY_2:String = "barrier_horizontal_gray_2";
        public static const BARRIER_HORIZONTAL_GRAY_3:String = "barrier_horizontal_gray_3";
        public static const BARRIER_HORIZONTAL_GRAY_4:String = "barrier_horizontal_gray_4";
        public static const BARRIER_HORIZONTAL_GREEN_0:String = "barrier_horizontal_green_0";
        public static const BARRIER_HORIZONTAL_GREEN_1:String = "barrier_horizontal_green_1";
        public static const BARRIER_HORIZONTAL_GREEN_2:String = "barrier_horizontal_green_2";
        public static const BARRIER_HORIZONTAL_GREEN_3:String = "barrier_horizontal_green_3";
        public static const BARRIER_HORIZONTAL_GREEN_4:String = "barrier_horizontal_green_4";
        public static const BARRIER_HORIZONTAL_ORANGE_0:String = "barrier_horizontal_orange_0";
        public static const BARRIER_HORIZONTAL_ORANGE_1:String = "barrier_horizontal_orange_1";
        public static const BARRIER_HORIZONTAL_ORANGE_2:String = "barrier_horizontal_orange_2";
        public static const BARRIER_HORIZONTAL_ORANGE_3:String = "barrier_horizontal_orange_3";
        public static const BARRIER_HORIZONTAL_ORANGE_4:String = "barrier_horizontal_orange_4";
        public static const BARRIER_HORIZONTAL_RED_0:String = "barrier_horizontal_red_0";
        public static const BARRIER_HORIZONTAL_RED_1:String = "barrier_horizontal_red_1";
        public static const BARRIER_HORIZONTAL_RED_2:String = "barrier_horizontal_red_2";
        public static const BARRIER_HORIZONTAL_RED_3:String = "barrier_horizontal_red_3";
        public static const BARRIER_HORIZONTAL_RED_4:String = "barrier_horizontal_red_4";
        public static const BARRIER_VERTICAL_BLUE_0:String = "barrier_vertical_blue_0";
        public static const BARRIER_VERTICAL_BLUE_1:String = "barrier_vertical_blue_1";
        public static const BARRIER_VERTICAL_BLUE_2:String = "barrier_vertical_blue_2";
        public static const BARRIER_VERTICAL_BLUE_3:String = "barrier_vertical_blue_3";
        public static const BARRIER_VERTICAL_BLUE_4:String = "barrier_vertical_blue_4";
        public static const BARRIER_VERTICAL_GRAY_0:String = "barrier_vertical_gray_0";
        public static const BARRIER_VERTICAL_GRAY_1:String = "barrier_vertical_gray_1";
        public static const BARRIER_VERTICAL_GRAY_2:String = "barrier_vertical_gray_2";
        public static const BARRIER_VERTICAL_GRAY_3:String = "barrier_vertical_gray_3";
        public static const BARRIER_VERTICAL_GRAY_4:String = "barrier_vertical_gray_4";
        public static const BARRIER_VERTICAL_GREEN_0:String = "barrier_vertical_green_0";
        public static const BARRIER_VERTICAL_GREEN_1:String = "barrier_vertical_green_1";
        public static const BARRIER_VERTICAL_GREEN_2:String = "barrier_vertical_green_2";
        public static const BARRIER_VERTICAL_GREEN_3:String = "barrier_vertical_green_3";
        public static const BARRIER_VERTICAL_GREEN_4:String = "barrier_vertical_green_4";
        public static const BARRIER_VERTICAL_ORANGE_0:String = "barrier_vertical_orange_0";
        public static const BARRIER_VERTICAL_ORANGE_1:String = "barrier_vertical_orange_1";
        public static const BARRIER_VERTICAL_ORANGE_2:String = "barrier_vertical_orange_2";
        public static const BARRIER_VERTICAL_ORANGE_3:String = "barrier_vertical_orange_3";
        public static const BARRIER_VERTICAL_ORANGE_4:String = "barrier_vertical_orange_4";
        public static const BARRIER_VERTICAL_RED_0:String = "barrier_vertical_red_0";
        public static const BARRIER_VERTICAL_RED_1:String = "barrier_vertical_red_1";
        public static const BARRIER_VERTICAL_RED_2:String = "barrier_vertical_red_2";
        public static const BARRIER_VERTICAL_RED_3:String = "barrier_vertical_red_3";
        public static const BARRIER_VERTICAL_RED_4:String = "barrier_vertical_red_4";
        public static const BLOB_1:String = "blob_1";
        public static const BLOB_2:String = "blob_2";
        public static const BLOB_3:String = "blob_3";
        public static const BOSS_FISH_DOWN_0:String = "boss_fish_down_0";
        public static const BOSS_FISH_DOWN_1:String = "boss_fish_down_1";
        public static const BOSS_FISH_DOWN_2:String = "boss_fish_down_2";
        public static const BOSS_FISH_LEFT_0:String = "boss_fish_left_0";
        public static const BOSS_FISH_LEFT_1:String = "boss_fish_left_1";
        public static const BOSS_FISH_LEFT_2:String = "boss_fish_left_2";
        public static const BOSS_FISH_RIGHT_0:String = "boss_fish_right_0";
        public static const BOSS_FISH_RIGHT_1:String = "boss_fish_right_1";
        public static const BOSS_FISH_RIGHT_2:String = "boss_fish_right_2";
        public static const BOSS_FISH_UP_0:String = "boss_fish_up_0";
        public static const BOSS_FISH_UP_1:String = "boss_fish_up_1";
        public static const BOSS_FISH_UP_2:String = "boss_fish_up_2";
        public static const BULLET_PENETRATING_LASER_0:String = "bullet_2_0";
        public static const BULLET_PENETRATING_LASER_1:String = "bullet_2_1";
        public static const BULLET_PENETRATING_LASER_2:String = "bullet_2_2";
        public static const BULLET_PENETRATING_LASER_3:String = "bullet_2_3";
        public static const BULLET_PENETRATING_LASER_4:String = "bullet_2_4";
        public static const BULLET_PENETRATING_LASER_5:String = "bullet_2_5";
        public static const CRATE_STRONG:String = "crate_strong";
        public static const CRATE_WEAK:String = "crate_weak";
        public static const DETECTOR_BLUE_0:String = "detector_blue_0";
        public static const DETECTOR_BLUE_1:String = "detector_blue_1";
        public static const DETECTOR_BLUE_2:String = "detector_blue_2";
        public static const DETECTOR_BLUE_3:String = "detector_blue_3";
        public static const DETECTOR_GRAY_0:String = "detector_gray_0";
        public static const DETECTOR_GRAY_1:String = "detector_gray_1";
        public static const DETECTOR_GRAY_2:String = "detector_gray_2";
        public static const DETECTOR_GRAY_3:String = "detector_gray_3";
        public static const DETECTOR_GREEN_0:String = "detector_green_0";
        public static const DETECTOR_GREEN_1:String = "detector_green_1";
        public static const DETECTOR_GREEN_2:String = "detector_green_2";
        public static const DETECTOR_GREEN_3:String = "detector_green_3";
        public static const DETECTOR_ORANGE_0:String = "detector_orange_0";
        public static const DETECTOR_ORANGE_1:String = "detector_orange_1";
        public static const DETECTOR_ORANGE_2:String = "detector_orange_2";
        public static const DETECTOR_ORANGE_3:String = "detector_orange_3";
        public static const DETECTOR_RAY_BLUE:String = "detector_ray_blue";
        public static const DETECTOR_RAY_GRAY:String = "detector_ray_gray";
        public static const DETECTOR_RAY_GREEN:String = "detector_ray_green";
        public static const DETECTOR_RAY_ORANGE:String = "detector_ray_orange";
        public static const DETECTOR_RAY_RED:String = "detector_ray_red";
        public static const DETECTOR_RED_0:String = "detector_red_0";
        public static const DETECTOR_RED_1:String = "detector_red_1";
        public static const DETECTOR_RED_2:String = "detector_red_2";
        public static const DETECTOR_RED_3:String = "detector_red_3";
        public static const DNA_0:String = "dna_0";
        public static const DNA_1:String = "dna_1";
        public static const DNA_2:String = "dna_2";
        public static const DNA_3:String = "dna_3";
        public static const DNA_4:String = "dna_4";
        public static const DNA_5:String = "dna_5";
        public static const DNA_6:String = "dna_6";
        public static const DNA_7:String = "dna_7";
        public static const DNA_8:String = "dna_8";
        public static const DNA_9:String = "dna_9";
        public static const DNA_SECRET_0:String = "dna_secret_0";
        public static const DNA_SECRET_1:String = "dna_secret_1";
        public static const DNA_SECRET_2:String = "dna_secret_2";
        public static const DNA_SECRET_3:String = "dna_secret_3";
        public static const DNA_SECRET_4:String = "dna_secret_4";
        public static const DNA_SECRET_5:String = "dna_secret_5";
        public static const DNA_SECRET_6:String = "dna_secret_6";
        public static const DNA_SECRET_7:String = "dna_secret_7";
        public static const DNA_SECRET_8:String = "dna_secret_8";
        public static const DNA_SECRET_9:String = "dna_secret_9";
        public static const DOCUMENT:String = "document";
        public static const DOOR_BLUE_0:String = "door_blue_0";
        public static const DOOR_BLUE_1:String = "door_blue_1";
        public static const DOOR_BLUE_2:String = "door_blue_2";
        public static const DOOR_BLUE_3:String = "door_blue_3";
        public static const DOOR_GRAY_0:String = "door_gray_0";
        public static const DOOR_GRAY_1:String = "door_gray_1";
        public static const DOOR_GRAY_2:String = "door_gray_2";
        public static const DOOR_GRAY_3:String = "door_gray_3";
        public static const DOOR_GREEN_0:String = "door_green_0";
        public static const DOOR_GREEN_1:String = "door_green_1";
        public static const DOOR_GREEN_2:String = "door_green_2";
        public static const DOOR_GREEN_3:String = "door_green_3";
        public static const DOOR_ORANGE_0:String = "door_orange_0";
        public static const DOOR_ORANGE_1:String = "door_orange_1";
        public static const DOOR_ORANGE_2:String = "door_orange_2";
        public static const DOOR_ORANGE_3:String = "door_orange_3";
        public static const DOOR_RED_0:String = "door_red_0";
        public static const DOOR_RED_1:String = "door_red_1";
        public static const DOOR_RED_2:String = "door_red_2";
        public static const DOOR_RED_3:String = "door_red_3";
        public static const EEL_BODY:String = "eel_mid_0";
        public static const EEL_HEAD:String = "eel_front_0";
        public static const EEL_TAIL:String = "eel_tail_0";
        public static const EMPTY:String = "empty";
        public static const ENTRANCE_DOWN:String = "level_entrance_down";
        public static const ENTRANCE_LEFT:String = "level_entrance_left";
        public static const ENTRANCE_RIGHT:String = "level_entrance_right";
        public static const ENTRANCE_UP:String = "level_entrance_up";
        public static const EYE_DOWN:String = "eye_down";
        public static const EYE_LEFT:String = "eye_left";
        public static const EYE_RIGHT:String = "eye_right";
        public static const EYE_UP:String = "eye_up";
        public static const FISH_DOWN_0:String = "fish_down_0";
        public static const FISH_DOWN_1:String = "fish_down_1";
        public static const FISH_DOWN_2:String = "fish_down_2";
        public static const FISH_LEFT_0:String = "fish_left_0";
        public static const FISH_LEFT_1:String = "fish_left_1";
        public static const FISH_LEFT_2:String = "fish_left_2";
        public static const FISH_RIGHT_0:String = "fish_right_0";
        public static const FISH_RIGHT_1:String = "fish_right_1";
        public static const FISH_RIGHT_2:String = "fish_right_2";
        public static const FISH_UP_0:String = "fish_up_0";
        public static const FISH_UP_1:String = "fish_up_1";
        public static const FISH_UP_2:String = "fish_up_2";
        public static const GHOST_SUB_0:String = "ghostsub_0";
        public static const GHOST_SUB_1:String = "ghostsub_1";
        public static const GHOST_SUB_2:String = "ghostsub_2";
        public static const GHOST_SUB_3:String = "ghostsub_3";
        public static const GHOST_SUB_4:String = "ghostsub_4";
        public static const JELLYFISH_0:String = "jellyfish_0";
        public static const JELLYFISH_1:String = "jellyfish_1";
        public static const JELLYFISH_2:String = "jellyfish_2";
        public static const JELLYFISH_3:String = "jellyfish_3";
        public static const JELLYFISH_4:String = "jellyfish_4";
        public static const JELLYFISH_BABY_0:String = "jellyfish_baby_0";
        public static const JELLYFISH_BABY_1:String = "jellyfish_baby_1";
        public static const JELLYFISH_BABY_2:String = "jellyfish_baby_2";
        public static const JELLYFISH_BABY_3:String = "jellyfish_baby_3";
        public static const KEY_BLUE:String = "key_blue";
        public static const KEY_GRAY:String = "key_gray";
        public static const KEY_GREEN:String = "key_green";
        public static const KEY_ORANGE:String = "key_orange";
        public static const KEY_RED:String = "key_red";
        public static const LEVEL_GROUP_SCREEN:String = "screen_small_0";
        public static const MINE_0:String = "mine_0";
        public static const MINE_1:String = "mine_1";
        public static const MINE_2:String = "mine_2";
        public static const MINE_3:String = "mine_3";
        public static const MINE_4:String = "mine_4";
        public static const MINE_5:String = "mine_5";
        public static const MINE_6:String = "mine_6";
        public static const MINE_7:String = "mine_7";
        public static const MINE_8:String = "mine_8";
        public static const MINE_9:String = "mine_9";
        public static const MINE_10:String = "mine_10";
        public static const NUMBERS_BIG_GREEN:String = "numbers_big_0";
        public static const NUMBERS_BIG_ORANGE:String = "numbers_big_1";
        public static const NUMBERS_BIG_RED:String = "numbers_big_2";
        public static const PARTICLE_BUBBLE_0:String = "particle_bubble_0";
        public static const PARTICLE_BUBBLE_1:String = "particle_bubble_1";
        public static const PARTICLE_BUBBLE_2:String = "particle_bubble_2";
        public static const PARTICLE_BUBBLE_3:String = "particle_bubble_3";
        public static const PARTICLE_BUBBLE_4:String = "particle_bubble_4";
        public static const PARTICLE_BUBBLE_BLACK_0:String = "particle_blackbubble_0";
        public static const PARTICLE_BUBBLE_BLACK_1:String = "particle_blackbubble_1";
        public static const PARTICLE_BUBBLE_BLACK_2:String = "particle_blackbubble_2";
        public static const PARTICLE_BUBBLE_BLACK_3:String = "particle_blackbubble_3";
        public static const PARTICLE_BUBBLE_BLACK_4:String = "particle_blackbubble_4";
        public static const PARTICLE_EXPLOSION_A_0:String = "particle_explosion_0";
        public static const PARTICLE_EXPLOSION_A_1:String = "particle_explosion_1";
        public static const PARTICLE_EXPLOSION_A_2:String = "particle_explosion_2";
        public static const PARTICLE_EXPLOSION_A_3:String = "particle_explosion_3";
        public static const PARTICLE_EXPLOSION_A_4:String = "particle_explosion_4";
        public static const PARTICLE_EXPLOSION_A_5:String = "particle_explosion_5";
        public static const PARTICLE_EXPLOSION_A_6:String = "particle_explosion_6";
        public static const PARTICLE_EXPLOSION_A_7:String = "particle_explosion_7";
        public static const PARTICLE_EXPLOSION_A_8:String = "particle_explosion_8";
        public static const PARTICLE_EXPLOSION_A_9:String = "particle_explosion_9";
        public static const PARTICLE_EXPLOSION_A_10:String = "particle_explosion_10";
        public static const PARTICLE_EXPLOSION_B_0:String = "explosion_new_1_00";
        public static const PARTICLE_EXPLOSION_B_1:String = "explosion_new_1_01";
        public static const PARTICLE_EXPLOSION_B_2:String = "explosion_new_1_02";
        public static const PARTICLE_EXPLOSION_B_3:String = "explosion_new_1_03";
        public static const PARTICLE_EXPLOSION_B_4:String = "explosion_new_1_04";
        public static const PARTICLE_EXPLOSION_B_5:String = "explosion_new_1_05";
        public static const PARTICLE_EXPLOSION_B_6:String = "explosion_new_1_06";
        public static const PARTICLE_EXPLOSION_B_7:String = "explosion_new_1_07";
        public static const PARTICLE_EXPLOSION_B_8:String = "explosion_new_1_08";
        public static const PARTICLE_EXPLOSION_B_9:String = "explosion_new_1_09";
        public static const PARTICLE_EXPLOSION_B_10:String = "explosion_new_1_10";
        public static const PARTICLE_EXPLOSION_B_11:String = "explosion_new_1_11";
        public static const PARTICLE_EXPLOSION_B_12:String = "explosion_new_1_12";
        public static const PARTICLE_EXPLOSION_C_0:String = "explosion_new_2_00";
        public static const PARTICLE_EXPLOSION_C_1:String = "explosion_new_2_01";
        public static const PARTICLE_EXPLOSION_C_2:String = "explosion_new_2_02";
        public static const PARTICLE_EXPLOSION_C_3:String = "explosion_new_2_03";
        public static const PARTICLE_EXPLOSION_C_4:String = "explosion_new_2_04";
        public static const PARTICLE_EXPLOSION_C_5:String = "explosion_new_2_05";
        public static const PARTICLE_EXPLOSION_C_6:String = "explosion_new_2_06";
        public static const PARTICLE_EXPLOSION_C_7:String = "explosion_new_2_07";
        public static const PARTICLE_EXPLOSION_C_8:String = "explosion_new_2_08";
        public static const PARTICLE_EXPLOSION_C_9:String = "explosion_new_2_09";
        public static const PARTICLE_EXPLOSION_C_10:String = "explosion_new_2_10";
        public static const PARTICLE_EXPLOSION_C_11:String = "explosion_new_2_11";
        public static const PARTICLE_EXPLOSION_C_12:String = "explosion_new_2_12";
        public static const PARTICLE_EXPLOSION_C_13:String = "explosion_new_2_13";
        public static const PARTICLE_EXPLOSION_C_14:String = "explosion_new_2_14";
        public static const PARTICLE_EXPLOSION_D_0:String = "explosion_new_3_00";
        public static const PARTICLE_EXPLOSION_D_1:String = "explosion_new_3_01";
        public static const PARTICLE_EXPLOSION_D_2:String = "explosion_new_3_02";
        public static const PARTICLE_EXPLOSION_D_3:String = "explosion_new_3_03";
        public static const PARTICLE_EXPLOSION_D_4:String = "explosion_new_3_04";
        public static const PARTICLE_EXPLOSION_D_5:String = "explosion_new_3_05";
        public static const PARTICLE_EXPLOSION_D_6:String = "explosion_new_3_06";
        public static const PARTICLE_EXPLOSION_D_7:String = "explosion_new_3_07";
        public static const PARTICLE_EXPLOSION_D_8:String = "explosion_new_3_08";
        public static const PARTICLE_EXPLOSION_D_9:String = "explosion_new_3_09";
        public static const PARTICLE_EXPLOSION_D_10:String = "explosion_new_3_10";
        public static const PARTICLE_EXPLOSION_D_11:String = "explosion_new_3_11";
        public static const PARTICLE_EXPLOSION_D_12:String = "explosion_new_3_12";
        public static const PARTICLE_EXPLOSION_D_13:String = "explosion_new_3_13";
        public static const PARTICLE_EXPLOSION_D_14:String = "explosion_new_3_14";
        public static const PLAYER_0:String = "player_0";
        public static const PLAYER_1:String = "player_1";
        public static const PLAYER_2:String = "player_2";
        public static const PLAYER_3:String = "player_3";
        public static const PLAYER_4:String = "player_4";
        public static const SHELL_BULLET:String = "shell_bullet";
        public static const SHELL_BULLET_EXPLOSION_0:String = "shell_bullet_explosion_0";
        public static const SHELL_BULLET_EXPLOSION_1:String = "shell_bullet_explosion_1";
        public static const SHELL_BULLET_EXPLOSION_2:String = "shell_bullet_explosion_2";
        public static const SHELL_BULLET_EXPLOSION_3:String = "shell_bullet_explosion_3";
        public static const SHELL_BULLET_EXPLOSION_4:String = "shell_bullet_explosion_4";
        public static const SHELL_BULLET_EXPLOSION_5:String = "shell_bullet_explosion_5";
        public static const SHELL_DOWN_0:String = "shell_down_0";
        public static const SHELL_DOWN_1:String = "shell_down_1";
        public static const SHELL_DOWN_2:String = "shell_down_2";
        public static const SHELL_DOWN_3:String = "shell_down_3";
        public static const SHELL_LEFT_0:String = "shell_left_0";
        public static const SHELL_LEFT_1:String = "shell_left_1";
        public static const SHELL_LEFT_2:String = "shell_left_2";
        public static const SHELL_LEFT_3:String = "shell_left_3";
        public static const SHELL_RIGHT_0:String = "shell_right_0";
        public static const SHELL_RIGHT_1:String = "shell_right_1";
        public static const SHELL_RIGHT_2:String = "shell_right_2";
        public static const SHELL_RIGHT_3:String = "shell_right_3";
        public static const SHELL_UP_0:String = "shell_up_0";
        public static const SHELL_UP_1:String = "shell_up_1";
        public static const SHELL_UP_2:String = "shell_up_2";
        public static const SHELL_UP_3:String = "shell_up_3";
        public static const SPIKES_0:String = "spikes_0";
        public static const SPIKES_1:String = "spikes_1";
        public static const SPIKES_2:String = "spikes_2";
        public static const SPIKES_3:String = "spikes_3";
        public static const SPIKES_4:String = "spikes_4";
        public static const SPIN_BLADE:String = "spin_blade";
        public static const SPONGE_0:String = "sponge_0";
        public static const SPONGE_1:String = "sponge_1";
        public static const SPONGE_2:String = "sponge_2";
        public static const SPONGE_3:String = "sponge_3";
        public static const SPONGE_4:String = "sponge_4";
        public static const SPONGE_5:String = "sponge_5";
        public static const SPONGE_DEAD_0:String = "sponge_dead_0";
        public static const SPONGE_DEAD_1:String = "sponge_dead_1";
        public static const SPONGE_DEAD_2:String = "sponge_dead_2";
        public static const SPONGE_DEAD_3:String = "sponge_dead_3";
        public static const SPONGE_DEAD_4:String = "sponge_dead_4";
        public static const SPONGE_DEAD_5:String = "sponge_dead_5";
        public static const TORPEDO_DOWN:String = "torpedo_down";
        public static const TORPEDO_LEFT:String = "torpedo_left";
        public static const TORPEDO_RIGHT:String = "torpedo_right";
        public static const TORPEDO_UP:String = "torpedo_up";
        public static const TRANSITION_BACKGROUND:String = "transition";
        public static const TRIGGER_BLUE_0:String = "trigger_blue_0";
        public static const TRIGGER_BLUE_1:String = "trigger_blue_1";
        public static const TRIGGER_BLUE_2:String = "trigger_blue_2";
        public static const TRIGGER_BLUE_3:String = "trigger_blue_3";
        public static const TRIGGER_BLUE_4:String = "trigger_blue_4";
        public static const TRIGGER_GRAY_0:String = "trigger_gray_0";
        public static const TRIGGER_GRAY_1:String = "trigger_gray_1";
        public static const TRIGGER_GRAY_2:String = "trigger_gray_2";
        public static const TRIGGER_GRAY_3:String = "trigger_gray_3";
        public static const TRIGGER_GRAY_4:String = "trigger_gray_4";
        public static const TRIGGER_GREEN_0:String = "trigger_green_0";
        public static const TRIGGER_GREEN_1:String = "trigger_green_1";
        public static const TRIGGER_GREEN_2:String = "trigger_green_2";
        public static const TRIGGER_GREEN_3:String = "trigger_green_3";
        public static const TRIGGER_GREEN_4:String = "trigger_green_4";
        public static const TRIGGER_ORANGE_0:String = "trigger_orange_0";
        public static const TRIGGER_ORANGE_1:String = "trigger_orange_1";
        public static const TRIGGER_ORANGE_2:String = "trigger_orange_2";
        public static const TRIGGER_ORANGE_3:String = "trigger_orange_3";
        public static const TRIGGER_ORANGE_4:String = "trigger_orange_4";
        public static const TRIGGER_RED_0:String = "trigger_red_0";
        public static const TRIGGER_RED_1:String = "trigger_red_1";
        public static const TRIGGER_RED_2:String = "trigger_red_2";
        public static const TRIGGER_RED_3:String = "trigger_red_3";
        public static const TRIGGER_RED_4:String = "trigger_red_4";
        public static const TURTLE_CCW_DOWN_0:String = "turtle_ccw_down_0";
        public static const TURTLE_CCW_DOWN_1:String = "turtle_ccw_down_1";
        public static const TURTLE_CCW_DOWN_2:String = "turtle_ccw_down_2";
        public static const TURTLE_CCW_LEFT_0:String = "turtle_ccw_left_0";
        public static const TURTLE_CCW_LEFT_1:String = "turtle_ccw_left_1";
        public static const TURTLE_CCW_LEFT_2:String = "turtle_ccw_left_2";
        public static const TURTLE_CCW_RIGHT_0:String = "turtle_ccw_right_0";
        public static const TURTLE_CCW_RIGHT_1:String = "turtle_ccw_right_1";
        public static const TURTLE_CCW_RIGHT_2:String = "turtle_ccw_right_2";
        public static const TURTLE_CCW_UP_0:String = "turtle_ccw_up_0";
        public static const TURTLE_CCW_UP_1:String = "turtle_ccw_up_1";
        public static const TURTLE_CCW_UP_2:String = "turtle_ccw_up_2";
        public static const TURTLE_CW_DOWN_0:String = "turtle_cw_down_0";
        public static const TURTLE_CW_DOWN_1:String = "turtle_cw_down_1";
        public static const TURTLE_CW_DOWN_2:String = "turtle_cw_down_2";
        public static const TURTLE_CW_LEFT_0:String = "turtle_cw_left_0";
        public static const TURTLE_CW_LEFT_1:String = "turtle_cw_left_1";
        public static const TURTLE_CW_LEFT_2:String = "turtle_cw_left_2";
        public static const TURTLE_CW_RIGHT_0:String = "turtle_cw_right_0";
        public static const TURTLE_CW_RIGHT_1:String = "turtle_cw_right_1";
        public static const TURTLE_CW_RIGHT_2:String = "turtle_cw_right_2";
        public static const TURTLE_CW_UP_0:String = "turtle_cw_up_0";
        public static const TURTLE_CW_UP_1:String = "turtle_cw_up_1";
        public static const TURTLE_CW_UP_2:String = "turtle_cw_up_2";
        public static const WHITE_SQUARE:String = "white_square";


        public static function getKeySpriteName(key:BonusKey):String {
            switch (key.color) {
                case(LockColor.RED):
                    return KEY_RED;
                case(LockColor.GREEN):
                    return KEY_GREEN;
                case(LockColor.BLUE):
                    return KEY_BLUE;
                case(LockColor.ORANGE):
                    return KEY_ORANGE;
                case(LockColor.GRAY):
                    return KEY_GRAY;
                default:
                    throw new ArgumentError("Invalid key color");
            }
        }

        public static function getDetectorRaySpriteName(detector:ObjectDetector):String {
            switch (detector.color) {
                case(LockColor.RED):
                    return DETECTOR_RAY_RED;
                case(LockColor.GREEN):
                    return DETECTOR_RAY_GREEN;
                case(LockColor.BLUE):
                    return DETECTOR_RAY_BLUE;
                case(LockColor.ORANGE):
                    return DETECTOR_RAY_ORANGE;
                case(LockColor.GRAY):
                    return DETECTOR_RAY_GRAY;
                default:
                    throw new ArgumentError("Invalid detector ray color");
            }
        }
        public static function getDoorSpriteName(color:LockColor):String {
            switch (color) {
                case(LockColor.RED):
                    return DOOR_RED_0;
                case(LockColor.GREEN):
                    return DOOR_GREEN_0;
                case(LockColor.BLUE):
                    return DOOR_BLUE_0;
                case(LockColor.ORANGE):
                    return DOOR_ORANGE_0;
                case(LockColor.GRAY):
                    return DOOR_GRAY_0;
                default:
                    throw new ArgumentError("Invalid door color");
            }
        }
    }
}
