function draw_items(argument0, argument1, argument2, argument3, argument4, argument5) {
	switch(argument0){
	    case(0):exit;
	    case(1):
	        draw_sprite(Wall,0,argument1,argument2)
	    exit;
	    case(2):
	        draw_sprite_ext(Blockers,0,argument1,argument2,1,1,0,color[argument3],1)
	            if argument4>0{
	                draw_rectangle_color(argument1+10,argument2+14,argument1+25,argument2+25,c_black,c_black,c_black,c_black,0)
	                draw_set_font(font0)
	                draw_set_halign(fa_right)
	                draw_text_color(argument1+25,argument2+12,string_hash_to_newline(string(argument4)),c_white,c_white,c_white,c_white,1)
	                draw_set_halign(fa_left)
	            }
	    exit;
	    case(3):
	        draw_sprite_ext(Colourer,0,argument1,argument2,1,1,0,color[argument3],1)
	    exit;
	    case(16):
	        draw_sprite(Spikes,argument3,argument1,argument2)
	    exit;
	    case(17):
	        draw_sprite(Bouncer,argument3,argument1,argument2)
	    exit;
	    case(18):
	        draw_sprite(Bouncer,2+argument3,argument1,argument2)
	    exit;
	    case(19):
	        draw_sprite(Rotter,argument3,argument1,argument2)
	    exit;
	    case(20):
	        draw_sprite(Rotter,4+argument3,argument1,argument2)
	    exit;
	    case(21):
	        draw_sprite(Thorner_O,argument3,argument1,argument2)
	    exit;
	    case(22):
	        draw_sprite(Thorner_D,argument3,argument1,argument2)
	    exit;
	    case(48):
	        draw_sprite_ext(Door,argument3 mod 4,argument1,argument2,1,1,0,color[floor(argument3/4)],1)
	        draw_sprite(Door_Ycon,argument5,argument1,argument2)
	            draw_rectangle_color(argument1+10,argument2+14,argument1+25,argument2+25,c_black,c_black,c_black,c_black,0)
	            draw_set_font(font0)
	            draw_set_halign(fa_right)
	            draw_text_color(argument1+25,argument2+12,string_hash_to_newline(string(argument4)),c_white,c_white,c_white,c_white,1)
	            draw_set_halign(fa_left)
	    exit;
	    case(49):
	        draw_sprite_ext(Button,0,argument1,argument2,1,1,0,color[argument4],1)
	            draw_rectangle_color(argument1+10,argument2+14,argument1+25,argument2+25,c_black,c_black,c_black,c_black,0)
	            draw_set_font(font0)
	            draw_set_halign(fa_right)
	            draw_text_color(argument1+25,argument2+12,string_hash_to_newline(string(argument3)),c_white,c_white,c_white,c_white,1)
	            draw_set_halign(fa_left)
	    exit;
	    case(50):
	        draw_sprite_ext(Switch,argument5,argument1,argument2,1,1,0,color[argument4],1)
	            draw_rectangle_color(argument1+10,argument2+14,argument1+25,argument2+25,c_black,c_black,c_black,c_black,0)
	            draw_set_font(font0)
	            draw_set_halign(fa_right)
	            draw_text_color(argument1+25,argument2+12,string_hash_to_newline(string(argument3)),c_white,c_white,c_white,c_white,1)
	            draw_set_halign(fa_left)
	    exit;
	    case(51):
	        draw_sprite(Crate,0,argument1,argument2)
	    exit;
	    case(52):
	        draw_set_blend_mode(bm_subtract);
	        draw_sprite_ext(Arrow,argument3,argument1,argument2,1,1,0,c_white,0.2)
	        draw_set_blend_mode(bm_add);
	        draw_sprite_ext(Arrow,argument3+4,argument1,argument2,1,1,0,c_white,0.2)
	        draw_set_blend_mode(bm_normal)
	    exit;
	    case(253):
	        draw_sprite(Bigdoor,0,argument1,argument2)
	    exit;
	    case(254):
	        draw_sprite(Talker,argument5,argument1,argument2)
	            draw_rectangle_color(argument1,argument2+14,argument1+25,argument2+25,c_black,c_black,c_black,c_black,0)
	            draw_set_font(font0)
	            draw_set_halign(fa_right)
	            draw_text_color(argument1+25,argument2+12,string_hash_to_newline(string(argument3)),c_white,c_white,c_white,c_white,1)
	            draw_set_halign(fa_left)
	            draw_text_color(argument1,argument2+12,string_hash_to_newline(string(argument4)),c_white,c_white,c_white,c_white,1)
	    exit;
	    case(255):
	        draw_sprite(Player,0,argument1,argument2)
	    exit;
	}

	draw_rectangle_color(argument1,argument2,argument1+25,argument2+25,c_black,c_black,c_black,c_black,0)
	draw_set_font(font0)
	                draw_set_halign(fa_right)
	                draw_text_color(argument1+25,argument2+10,string_hash_to_newline(string(argument0)),c_white,c_white,c_white,c_white,1)
	                draw_set_halign(fa_left)



}
